// AUTO-GENERATED by tools/src/generate-content.mjs — do not edit directly.
// Source files: content/blog/<folder>/<lang>.md and content/wiki/pushup-types/<id>.<lang>.md
// (any lowercase locale code is accepted, not just de/en).
// Run `pnpm nx run tools:generate-content` to regenerate (also runs automatically
// before `pnpm nx run web:build`).

export interface ExerciseWikiContent {
  readonly name: string;
  readonly summary: string;
  readonly instructions: ReadonlyArray<string>;
  readonly tips: ReadonlyArray<string>;
}

/**
 * Translatable wiki copy for non-pushup exercises. Keys are the
 * `ExerciseDefinition.id` (dotted segments like `abs.situps`); values
 * are per-locale content blocks. Locales without a translation fall
 * back through `en` → `de` in `localizeExerciseWiki`.
 */
export const EXERCISE_WIKI_CONTENT: Readonly<
  Record<string, Readonly<Record<string, ExerciseWikiContent>>>
> = {
  'abs.crunches': {
    de: {
      name: 'Crunches',
      summary:
        'Kurzes Aufrollen des oberen Rückens — gezielter Reiz für den geraden Bauchmuskel ohne Hüftbeuger.',
      instructions: [
        'Auf den Rücken legen, Knie gebeugt, Füße flach am Boden.',
        'Hände leicht hinter den Ohren oder vor der Brust.',
        'Nur die Schulterblätter vom Boden lösen — der untere Rücken bleibt liegen.',
        'Kontrolliert zurück, ohne die Spannung komplett zu verlieren.',
      ],
      tips: [
        'Kinn locker zur Brust, aber nicht aktiv ziehen — der Bauch macht die Arbeit, nicht der Hals.',
        'Bei jeder Wiederholung kurz oben pausieren (1 s) für mehr Reiz bei gleicher Wiederholungszahl.',
      ],
    },
    en: {
      name: 'Crunches',
      summary:
        'Short upper-back curl — isolates the rectus abdominis without the hip flexors taking over.',
      instructions: [
        'Lie on your back, knees bent, feet flat on the floor.',
        'Hands lightly behind the ears or crossed over the chest.',
        'Lift only the shoulder blades off the floor — the lower back stays grounded.',
        'Lower under control, never fully losing tension at the bottom.',
      ],
      tips: [
        'Chin loose toward the chest, but do not actively pull — the abs do the work, not the neck.',
        'Add a 1-second hold at the top to increase the stimulus at the same rep count.',
      ],
    },
  },
  'abs.legraises': {
    de: {
      name: 'Beinheben',
      summary:
        'Beinheben aus dem Liegen oder Hang — trifft besonders den unteren Bauchbereich.',
      instructions: [
        'Liegend mit Rücken am Boden oder hängend an einer Klimmzugstange.',
        'Beine gestreckt oder leicht gebeugt, langsam Richtung Decke heben.',
        'Lendenwirbelsäule (am Boden) bzw. der Oberkörper (im Hang) bleibt ruhig — kein Schwingen.',
        'Kontrolliert absenken, ohne in den Boden zu krachen bzw. ohne durchzuschwingen.',
      ],
      tips: [
        'Progression: Knie angezogen → Knie zum Brustkorb → gestreckte Beine waagerecht.',
        'Schulterblätter im Hang aktiv nach unten ziehen, sonst macht der Schultergürtel die Arbeit.',
      ],
    },
    en: {
      name: 'Leg Raises',
      summary:
        'Lying or hanging leg raises — emphasise the lower portion of the abdominal wall.',
      instructions: [
        'Either lie on your back or hang from a pull-up bar.',
        'Legs straight or slightly bent, lift them slowly toward the ceiling.',
        'Lumbar spine (lying) or torso (hanging) stays still — no swinging.',
        'Lower under control, no slamming into the floor and no kipping at the bottom.',
      ],
      tips: [
        'Progression: knees tucked → knees to chest → straight legs to horizontal.',
        'In the hang, actively depress the shoulder blades or the shoulder girdle ends up doing the work.',
      ],
    },
  },
  'abs.mountainclimbers': {
    de: {
      name: 'Mountain Climbers',
      summary:
        'Schnelle Beinwechsel aus der Liegestütz-Position — Bauch, Hüftbeuger und Kreislauf in einem.',
      instructions: [
        'Hochstütz wie bei einer Liegestütze, Hände unter den Schultern, Körper als gerade Linie.',
        'Ein Knie zur Brust ziehen, dann zurück, gleichzeitig das andere nach vorn.',
        'Tempo wählbar — schnell für Cardio-Reiz, langsam für mehr Bauchspannung.',
        'Hüfte bleibt niedrig — nicht hochschieben oder zur Seite kippen.',
      ],
      tips: [
        'Zähle "links + rechts = 1 Wiederholung" für konsistente Trainingsprotokolle.',
        'Variante: Cross-Body (Knie zum gegenüberliegenden Ellenbogen) trifft die schrägen Bauchmuskeln stärker.',
      ],
    },
    en: {
      name: 'Mountain Climbers',
      summary:
        'Fast alternating knee drives from a push-up position — abs, hip flexors and cardio in one.',
      instructions: [
        'High plank like a push-up start, hands under the shoulders, body in a straight line.',
        'Pull one knee to the chest, then return it as the other drives forward.',
        'Tempo is your choice — fast for cardio, slow for more abdominal tension.',
        'Hips stay low — no piking up or rocking side to side.',
      ],
      tips: [
        'Count "left + right = 1 rep" so logs stay consistent.',
        'Variant: cross-body (knee to the opposite elbow) hits the obliques more.',
      ],
    },
  },
  'abs.russiantwist': {
    de: {
      name: 'Russian Twist',
      summary:
        'Rotation des Oberkörpers im Sitzen — Rotationskraft und schräge Bauchmuskeln.',
      instructions: [
        'Auf das Gesäß setzen, Knie gebeugt, Füße angehoben oder auf dem Boden.',
        'Oberkörper leicht zurücklehnen, gerader Rücken (kein runder Buckel).',
        'Hände vor der Brust falten (oder mit Gewicht); rhythmisch links–rechts rotieren.',
        'Bewegung kommt aus dem Rumpf, nicht aus den Armen.',
      ],
      tips: [
        'Schwerer machen mit einer Hantel, Kettlebell oder Wasserflasche.',
        'Eine Wiederholung = einmal links und einmal rechts.',
      ],
    },
    en: {
      name: 'Russian Twist',
      summary: 'Seated torso rotation — rotational strength and obliques.',
      instructions: [
        'Sit on your glutes, knees bent, feet either lifted or grounded.',
        'Lean the torso slightly back with a flat (not rounded) back.',
        'Hands clasped in front of the chest (or holding a weight); rotate left–right rhythmically.',
        'Movement comes from the trunk, not from the arms.',
      ],
      tips: [
        'Load with a dumbbell, kettlebell or water bottle to scale up.',
        'One rep = one twist to the left AND one to the right.',
      ],
    },
  },
  'abs.situps': {
    de: {
      name: 'Sit-ups',
      summary:
        'Klassisches Bauchaufrollen aus der Rückenlage bis in den Sitz — die einfachste Form direkter Bauchmuskelarbeit.',
      instructions: [
        'Auf den Rücken legen, Knie gebeugt, Füße flach auf dem Boden (fixiert oder unter etwas geklemmt).',
        'Hände hinter dem Kopf oder über der Brust verschränken — Hals nicht ziehen.',
        'Oberkörper mit Bauchspannung kontrolliert hochrollen, bis du aufrecht sitzt.',
        'Genauso kontrolliert wieder ablegen — nicht in den Boden fallen lassen.',
      ],
      tips: [
        'Bei Nackenproblemen lieber Crunches oder Dead Bug wählen.',
        'Decline-Variante (Beine erhöht) macht es spürbar härter.',
      ],
    },
    en: {
      name: 'Sit-ups',
      summary:
        'Classic torso curl from supine to upright sitting — the simplest direct ab exercise.',
      instructions: [
        'Lie on your back, knees bent, feet flat on the floor (anchored or tucked under something).',
        'Hands behind the head or crossed over the chest — do not yank on the neck.',
        'Curl the torso up under abdominal control until you sit upright.',
        'Lower back down with the same control — do not drop into the floor.',
      ],
      tips: [
        'If your neck complains, use crunches or dead bugs instead.',
        'The decline variant (feet elevated) makes it noticeably harder.',
      ],
    },
  },
  'cardio.burpees': {
    de: {
      name: 'Burpees',
      summary:
        'Ganzkörper-Cardio aus Hocke, Liegestütze und Sprung — der härteste Standard-Move ohne Equipment.',
      instructions: [
        'Aufrecht stehen, in eine Hocke gehen und die Hände vor den Füßen aufsetzen.',
        'Beide Beine nach hinten in die Plank-Position springen, optional eine Liegestütze ausführen.',
        'Beide Beine wieder unter den Körper springen, in die Hocke.',
        'Mit einem Strecksprung explosiv nach oben, Hände kurz über dem Kopf klatschen.',
      ],
      tips: [
        'Tempo nach Trainingsstand wählen — Form schlägt Geschwindigkeit.',
        'Skalierung: Liegestütze weglassen, Sprung durch Aufstehen ersetzen — beides macht es zugänglicher.',
      ],
    },
    en: {
      name: 'Burpees',
      summary:
        'Full-body cardio from squat to push-up to jump — the toughest no-equipment standard.',
      instructions: [
        'Stand tall, drop into a squat and place the hands in front of the feet.',
        'Jump both legs back into a plank, optionally perform one push-up.',
        'Jump the legs forward under the body, back into a squat.',
        'Explode up into a jump, hands clapping briefly over the head.',
      ],
      tips: [
        'Choose tempo by training age — form beats speed.',
        'Scaling: skip the push-up; replace the jump with standing up — both make it accessible.',
      ],
    },
  },
  'cardio.cycling': {
    de: {
      name: 'Radfahren',
      summary:
        'Gelenkschonendes Ausdauertraining auf Straße, Trail oder Indoor-Bike.',
      instructions: [
        'Sitzhöhe so wählen, dass das Knie unten leicht (10-15°) gebeugt bleibt — kein durchgestrecktes Bein.',
        'Trittfrequenz 80-100 Umdrehungen pro Minute für effizientes Treten; weniger Drehmoment, weniger Knieverschleiß.',
        'Hände locker am Lenker, Schultern entspannt — nicht hochziehen.',
        'Atmung gleichmäßig anpassen an das gefahrene Tempo.',
      ],
      tips: [
        'Geschätzte Belastung über Wattmessung oder Herzfrequenz — reines "Gefühl" ist trügerisch.',
        'Klick-Pedale erhöhen Effizienz, brauchen aber Eingewöhnung.',
      ],
    },
    en: {
      name: 'Cycling',
      summary:
        'Joint-friendly endurance training on road, trail or indoor bike.',
      instructions: [
        'Set the saddle so the knee stays slightly (10-15°) bent at the bottom — no fully extended leg.',
        'Cadence 80-100 rpm for efficient pedalling — less torque, less knee wear.',
        'Hands relaxed on the bar, shoulders down — not shrugged.',
        'Adapt breathing to the pace.',
      ],
      tips: [
        'Gauge effort with power (watts) or heart rate — pure "feel" is misleading.',
        'Clip pedals raise efficiency but need a few rides to get used to.',
      ],
    },
  },
  'cardio.highknees': {
    de: {
      name: 'High Knees',
      summary:
        'Laufen auf der Stelle mit hohem Kniehub — Pulsbeschleuniger und Hüftbeuger-Training.',
      instructions: [
        'Aufrecht stehen, Arme im Boxer-Winkel.',
        'Knie abwechselnd auf Hüfthöhe (oder höher) ziehen — Tempo zügig.',
        'Auf den Fußballen aufkommen, weich federnd.',
        'Oberkörper aufrecht — nicht nach vorn klappen, um die Knie zu erreichen.',
      ],
      tips: [
        'Als Cardio-Burst zwischen Sätzen (30-60 s) eingesetzt — kein Equipment, viel Reiz.',
        'Wenn die Knie nicht hoch kommen, ist es Joggen auf der Stelle — keine Übung.',
      ],
    },
    en: {
      name: 'High Knees',
      summary:
        'Running in place with high knee drive — heart rate booster and hip flexor primer.',
      instructions: [
        'Stand tall, arms at boxer angle.',
        'Alternate driving the knees up to hip height (or higher) at a fast pace.',
        'Land on the balls of the feet, springy and quiet.',
        'Stay upright — don\'t lean forward to "meet" the knees.',
      ],
      tips: [
        'Great cardio burst between sets (30-60 s) — no gear, plenty of stimulus.',
        "If the knees don't come up, it's jogging in place — not the exercise.",
      ],
    },
  },
  'cardio.jumpingjacks': {
    de: {
      name: 'Hampelmänner',
      summary:
        'Klassisches Aufwärm- und Cardio-Element — Schultern, Hüfte und Kreislauf in einem.',
      instructions: [
        'Aufrecht stehen, Füße zusammen, Arme an den Seiten.',
        'Im Sprung Beine seitlich öffnen, gleichzeitig Arme über den Kopf führen.',
        'Im nächsten Sprung zurück in die Ausgangsposition.',
        'Rhythmisch durchgehend, weich auf den Fußballen landen.',
      ],
      tips: [
        'Perfektes Aufwärmen vor Pushup- oder Lauf-Einheit — 2-3 Minuten reichen.',
        'Knieprobleme? Step-Touch-Variante (statt springen seitlich treten) bietet niedrigeren Impact.',
      ],
    },
    en: {
      name: 'Jumping Jacks',
      summary:
        'Classic warm-up and cardio move — shoulders, hips and heart rate in one.',
      instructions: [
        'Stand tall, feet together, arms by the sides.',
        'In one jump, spread the legs sideways while raising the arms overhead.',
        'On the next jump, return to the start.',
        'Keep it rhythmic, landing soft on the balls of the feet.',
      ],
      tips: [
        'Perfect warm-up before push-up or running sessions — 2-3 minutes is enough.',
        'Knees complaining? Step-touch instead of jumping for a low-impact variant.',
      ],
    },
  },
  'cardio.jumprope': {
    de: {
      name: 'Seilspringen',
      summary:
        'Hochintensives Cardio mit minimaler Ausrüstung — Wadenkraft, Koordination und Kondition.',
      instructions: [
        'Seil so einstellen, dass die Griffe in der Mitte des Brustbeins enden, wenn du auf der Mitte stehst.',
        'Aufrecht stehen, Ellenbogen am Körper, Bewegung nur aus den Handgelenken.',
        'Kleine, schnelle Sprünge — gerade so hoch, dass das Seil durchgeht (1-2 cm).',
        'Auf den Fußballen landen, Knie federn — kein Stampfen auf den Fersen.',
      ],
      tips: [
        'Anfänger zählen Sprünge in Sätzen (3 × 50); Fortgeschrittene über Zeit (3 × 60 s).',
        'Doppeltakt nicht erzwingen — erst sauberer Grund-Rhythmus, dann Tempo.',
      ],
    },
    en: {
      name: 'Jump Rope',
      summary:
        'High-intensity cardio with minimal gear — calf strength, coordination and conditioning.',
      instructions: [
        'Size the rope so the handles reach mid-sternum when you stand on the middle of it.',
        'Stand tall, elbows close to the body, the motion comes from the wrists.',
        'Small, fast hops — just enough to clear the rope (1-2 cm).',
        'Land on the balls of the feet, knees absorbing — no heel stomping.',
      ],
      tips: [
        'Beginners count reps in sets (3 × 50); advanced over time (3 × 60 s).',
        "Don't force double-unders — get a clean basic rhythm first, then add speed.",
      ],
    },
  },
  'cardio.rowing': {
    de: {
      name: 'Rudern (Indoor)',
      summary:
        'Ganzkörper-Cardio am Rudergerät — Beine, Rücken und Cardio in einem Zug.',
      instructions: [
        'Catch (Auszug): Knie gebeugt, Schienbeine senkrecht, Arme gestreckt, Oberkörper leicht vorgebeugt.',
        'Drive: zuerst die Beine durchdrücken, dann den Oberkörper aufrichten, zuletzt die Arme zur unteren Rippe ziehen.',
        'Finish: Beine gestreckt, Oberkörper leicht zurück (ca. 11 Uhr), Hände an der unteren Rippe.',
        'Recovery: in umgekehrter Reihenfolge — Arme strecken, Oberkörper nach vorn, Beine beugen.',
      ],
      tips: [
        '60-70 % der Kraft kommt aus den Beinen — nicht zu viel mit den Armen ziehen.',
        'Ziel-Schlagfrequenz 18-26 Züge pro Minute für Ausdauer; höher für Intervalle.',
      ],
    },
    en: {
      name: 'Rowing (Indoor)',
      summary:
        'Full-body cardio on the ergometer — legs, back and conditioning in one stroke.',
      instructions: [
        'Catch: knees bent, shins vertical, arms extended, torso slightly forward.',
        'Drive: push the legs first, then swing the torso back, finally pull the arms to the lower ribs.',
        "Finish: legs straight, torso leaning back slightly (~11 o'clock), hands at the lower ribs.",
        'Recovery: reverse the sequence — arms extend, torso forward, knees bend.',
      ],
      tips: [
        "60-70 % of the power comes from the legs — don't over-pull with the arms.",
        'Target stroke rate 18-26 spm for endurance; higher for intervals.',
      ],
    },
  },
  'cardio.running': {
    de: {
      name: 'Laufen',
      summary:
        'Klassisches Ausdauertraining — der einfachste Weg zu mehr Kondition und VO₂max.',
      instructions: [
        'Lockerer Stand, Schritte natürlich, leicht nach vorn geneigter Oberkörper.',
        'Mittelfußaufsatz (nicht reine Ferse) reduziert Stoßbelastung.',
        'Atmung gleichmäßig — bei lockerem Lauf 3 Schritte ein, 3 aus; bei härterem Tempo 2/2.',
        'Wöchentlich nicht mehr als 10 % Gesamtkilometer steigern (10%-Regel).',
      ],
      tips: [
        'Anfänger starten mit Walk/Run-Intervallen (1 min Lauf, 1 min Gehen).',
        'Schuhe und Laufgürtel-Tracker helfen, aber Konsistenz schlägt jedes Equipment.',
      ],
    },
    en: {
      name: 'Running',
      summary:
        'Classic endurance training — the easiest path to better conditioning and VO₂max.',
      instructions: [
        'Relaxed posture, steps natural, torso tilted slightly forward.',
        'Land on the mid-foot (not pure heel) to reduce impact.',
        'Breathe evenly — on easy runs 3 steps in, 3 out; at harder paces 2/2.',
        'Increase weekly mileage by no more than 10 % (the 10 % rule).',
      ],
      tips: [
        'Beginners start with walk/run intervals (1 min run, 1 min walk).',
        'Shoes and a running watch help, but consistency beats any gear.',
      ],
    },
  },
  'cardio.swimming': {
    de: {
      name: 'Schwimmen',
      summary:
        'Ganzkörper-Cardio im Wasser — gelenkschonend und atmungstechnisch fordernd.',
      instructions: [
        'Körperhaltung waagerecht — Hüfte und Beine nahe an die Wasseroberfläche bringen.',
        'Atmung beim Kraulen seitlich (alle 2-3 Züge), bei Brust frontal.',
        'Aus den Hüften, nicht aus den Knien beinarbeiten — kleine, schnelle Schläge.',
        'Lange, gleichmäßige Züge schlagen wilde Hektik — Effizienz vor Kraft.',
      ],
      tips: [
        'Anfangs lieber kürzere Strecken (4 × 50 m) mit Pausen als ein einziger Versuch über 200 m.',
        'Schwimmbrille reduziert Reibung und Reizung erheblich — Pflichtausstattung.',
      ],
    },
    en: {
      name: 'Swimming',
      summary:
        'Full-body cardio in the water — joint-friendly and breath-demanding.',
      instructions: [
        'Body horizontal — bring the hips and legs close to the surface.',
        'Breathe sideways every 2-3 strokes (freestyle), or forward (breaststroke).',
        'Kick from the hips, not the knees — small, fast strokes.',
        'Long, even pulls beat thrashing — efficiency over power.',
      ],
      tips: [
        'Start with short distances (4 × 50 m) and rest, rather than chasing one 200 m attempt.',
        'Goggles cut friction and irritation dramatically — non-negotiable kit.',
      ],
    },
  },
  'cardio.walking': {
    de: {
      name: 'Gehen',
      summary:
        'Zügiges Spazieren im Freien oder auf dem Laufband — der unterschätzteste Cardio-Reiz.',
      instructions: [
        'Aufrecht gehen, Schritte natürlich, Arme schwingen mit.',
        'Tempo "Brisk Walk" — du kannst noch sprechen, aber nicht mehr singen.',
        'Atmung durch die Nase, wenn möglich; bei Anstieg in Mund- und Nasen-Atmung wechseln.',
        '30-60 Minuten pro Einheit für Ausdauer; oder mehrere kurze Spaziergänge über den Tag verteilt.',
      ],
      tips: [
        '6-10 km/h auf flachem Terrain; Steigungen erhöhen den Trainingsreiz spürbar.',
        'Schuhwerk wichtiger als Tempo — unbequeme Schuhe ruinieren die Mobilität nach 30 Minuten.',
      ],
    },
    en: {
      name: 'Walking',
      summary:
        'Brisk walking outdoors or on a treadmill — the most underrated cardio stimulus.',
      instructions: [
        'Walk tall, steps natural, arms swinging.',
        'Brisk pace — you can still talk but not sing.',
        'Breathe through the nose if you can; switch to mouth+nose on inclines.',
        '30-60 minutes per session for endurance, or several short walks across the day.',
      ],
      tips: [
        '6-10 km/h on flat ground; hills bump the stimulus significantly.',
        'Footwear matters more than pace — bad shoes wreck your gait after 30 minutes.',
      ],
    },
  },
  'core.deadbug': {
    de: {
      name: 'Dead Bug',
      summary:
        'Anti-Extensions-Übung im Liegen — koordiniert Bauchspannung mit gegensätzlicher Arm- und Beinbewegung.',
      instructions: [
        'Auf den Rücken legen, Arme senkrecht nach oben, Knie zu 90° gebeugt über der Hüfte.',
        'Lendenwirbelsäule fest in den Boden drücken — kein Spalt zwischen Rücken und Matte.',
        'Gegenüberliegenden Arm und Bein gleichzeitig langsam absenken, ohne den Rücken zu heben.',
        'Kontrolliert zur Ausgangsposition zurück, dann die andere Seite.',
      ],
      tips: [
        'Wenn der Rücken abhebt, Arm/Bein weniger weit absenken oder Knie höher beugt halten.',
        'Tempo wichtiger als ROM — 3-4 s pro Seite ist besser als hektisches Hin-und-Her.',
      ],
    },
    en: {
      name: 'Dead Bug',
      summary:
        'Supine anti-extension drill — coordinates a braced core with contralateral arm and leg motion.',
      instructions: [
        'Lie on your back, arms pointing straight up, knees bent 90° over the hips.',
        'Press the lower back firmly into the floor — no gap between back and mat.',
        'Slowly lower the opposite arm and leg at the same time without lifting the back.',
        'Return under control, then switch sides.',
      ],
      tips: [
        'If the lower back lifts off, shorten the range or keep the knee bent higher.',
        'Tempo matters more than range — 3-4 s per side beats a rushed back-and-forth.',
      ],
    },
  },
  'core.hollowhold': {
    de: {
      name: 'Hollow Hold',
      summary:
        'Statische Bauchhaltung mit angehobenen Armen und Beinen — Grundlage für Turnübungen.',
      instructions: [
        'Auf den Rücken legen, Arme und Beine gestreckt nach oben.',
        'Schultern und Beine gleichzeitig anheben, sodass nur der untere Rücken den Boden berührt.',
        'Lendenwirbelsäule aktiv in den Boden pressen — die "Schale" (Hollow) muss bestehen bleiben.',
        'Position halten, gleichmäßig weiteratmen.',
      ],
      tips: [
        'Skalierung von leicht nach schwer: Tuck (Knie angezogen) → Halb-Hollow (Knie 90°) → Voll-Hollow (gestreckt).',
        'Anfänger: 3 × 15-20 s; Fortgeschrittene 3 × 45-60 s.',
      ],
    },
    en: {
      name: 'Hollow Hold',
      summary:
        'Static "hollow body" position with arms and legs raised — a foundation for gymnastic strength.',
      instructions: [
        'Lie on your back, arms and legs extended straight.',
        'Lift shoulders and legs simultaneously so only the lower back touches the floor.',
        'Actively press the lumbar spine into the floor — the dish ("hollow") must stay.',
        'Hold the position, breathing evenly throughout.',
      ],
      tips: [
        'Scale from easy to hard: tuck (knees pulled in) → half-hollow (knees 90°) → full hollow (extended).',
        'Beginners: 3 × 15-20 s; advanced 3 × 45-60 s.',
      ],
    },
  },
  'hinge.goodmorning': {
    de: {
      name: 'Good Morning',
      summary:
        'Hüftbeuge mit aufrechtem Oberkörper — dehnt und stärkt die hintere Kette.',
      instructions: [
        'Schulterbreiter Stand, Hände hinter dem Kopf oder auf den Schultern (oder Stange im Nacken).',
        'Knie minimal gebeugt, Hüfte langsam nach hinten schicken.',
        'Oberkörper kontrolliert nach vorn neigen, Rücken gerade — bis Spannung in den hinteren Oberschenkeln deutlich spürbar wird.',
        'Über die Ferse zurück in den aufrechten Stand drücken.',
      ],
      tips: [
        'Beweglichkeit limitiert die Tiefe — kein Hohlkreuz oder runder Rücken erzwingen.',
        '3-1-1 Tempo (3 s runter, 1 s unten, 1 s hoch) maximiert den Trainingsreiz mit wenig Gewicht.',
      ],
    },
    en: {
      name: 'Good Morning',
      summary:
        'Hip hinge with an upright torso — stretches and strengthens the posterior chain.',
      instructions: [
        'Shoulder-width stance, hands behind the head, on the shoulders (or a bar across the upper back).',
        'Knees minimally bent, push the hips back slowly.',
        "Tilt the torso forward under control with a flat back — until the hamstrings tell you they're working.",
        'Drive through the heels back to standing.',
      ],
      tips: [
        'Mobility limits depth — never force a lower-back arch or rounded back.',
        '3-1-1 tempo (3 s down, 1 s pause, 1 s up) maximises stimulus with little weight.',
      ],
    },
  },
  'hinge.singlelegRdl': {
    de: {
      name: 'Einbeiniges Kreuzheben',
      summary:
        'Hüftbeuge auf einem Bein — Balance, hintere Kette und Hüftstabilität in einer Übung.',
      instructions: [
        'Aufrecht stehen, Gewicht auf einem Bein, anderes Bein leicht abgehoben.',
        'Hüfte nach hinten schicken, Oberkörper kontrolliert nach vorn neigen — das hintere Bein streckt sich nach hinten als Gegengewicht.',
        'Rücken bleibt gerade, Standknie leicht gebeugt; bis zur Waagerechten oder so weit wie sauber möglich.',
        'Über die Ferse zurück in den aufrechten Stand drücken, dabei Hüfte nach vorn.',
      ],
      tips: [
        'Mit Gewicht (Kurzhantel, Wasserflasche) in der gegenüberliegenden Hand wird die Stabilität gefordert.',
        'Anfangs einen Fingerkontakt mit der Wand erlauben — Balance braucht Übung.',
      ],
    },
    en: {
      name: 'Single-Leg Romanian Deadlift',
      summary:
        'One-legged hip hinge — balance, posterior chain and hip stability in one drill.',
      instructions: [
        'Stand tall, weight on one leg, the other lightly lifted.',
        'Send the hips back and tilt the torso forward — the rear leg extends back as a counterweight.',
        'Keep a flat back, standing knee soft; hinge to horizontal or as far as form allows.',
        'Drive through the heel back to standing while pushing the hips forward.',
      ],
      tips: [
        'Holding a weight (dumbbell, water bottle) in the opposite hand raises the stability demand.',
        'Allow a fingertip on a wall in the beginning — single-leg balance takes practice.',
      ],
    },
  },
  'legs.calfraises': {
    de: {
      name: 'Wadenheben',
      summary:
        'Isoliertes Training der Wadenmuskeln — Sprungkraft und Stabilität für Knöchel und Knie.',
      instructions: [
        'Aufrecht stehen, Füße hüftbreit, Gewicht auf den Fußballen.',
        'Langsam auf die Zehenspitzen hochdrücken, oben kurz halten.',
        'Kontrolliert wieder absenken — Fersen nicht in den Boden krachen lassen.',
        'Maximale Range nutzen, wenn auf einer Treppenkante gestanden wird.',
      ],
      tips: [
        'Auf einer Stufe stehen (Ferse hängt in der Luft) für deutlich mehr Dehnung und Reiz.',
        'Hohe Wiederholungszahlen funktionieren besser für die Waden — 15-25 pro Satz.',
      ],
    },
    en: {
      name: 'Calf Raises',
      summary:
        'Isolated calf training — jump power and stability for ankles and knees.',
      instructions: [
        'Stand tall, feet hip-width, weight on the balls of the feet.',
        'Press slowly up onto the toes, pause briefly at the top.',
        'Lower under control — do not let the heels crash into the floor.',
        'Standing on a step edge unlocks the full range of motion.',
      ],
      tips: [
        'Stand on a step (heels hanging) for much more stretch and stimulus.',
        'High reps work better for calves — aim for 15-25 per set.',
      ],
    },
  },
  'legs.glutebridge': {
    de: {
      name: 'Hüftheben',
      summary:
        'Hüftstreckung aus der Rückenlage — direkt für den Po und die hintere Oberschenkelkette.',
      instructions: [
        'Auf den Rücken legen, Knie gebeugt, Füße flach am Boden, hüftbreit.',
        'Po aktiv anspannen und die Hüfte zur Decke drücken.',
        'Oben kurz halten (1 s) — der Körper bildet eine Linie zwischen Knien und Schultern.',
        'Kontrolliert wieder absenken — Po nur kurz aufsetzen, dann nächste Wiederholung.',
      ],
      tips: [
        'Druck kommt aus den Fersen, nicht aus den Zehenspitzen — sonst übernimmt die vordere Oberschenkelmuskulatur.',
        'Bei sehr starken Trainierenden Hüftheben mit einbeiniger Variante oder Gewicht progressieren.',
      ],
    },
    en: {
      name: 'Glute Bridge',
      summary:
        'Hip extension from supine — direct work for the glutes and posterior chain.',
      instructions: [
        'Lie on your back, knees bent, feet flat and hip-width on the floor.',
        'Squeeze the glutes and drive the hips up to the ceiling.',
        'Hold the top briefly (1 s) — body forms a line from knees to shoulders.',
        'Lower under control — touch down briefly, then go again.',
      ],
      tips: [
        'Drive through the heels, not the toes — toe-pressure shifts the load to the quads.',
        'Progress with a single-leg variant or added weight once bodyweight is too easy.',
      ],
    },
  },
  'legs.jumpsquats': {
    de: {
      name: 'Jump Squats',
      summary:
        'Explosive Kniebeuge mit Absprung — Schnellkraft und Beinleistung.',
      instructions: [
        'Wie eine normale Kniebeuge absenken.',
        'Aus der unteren Position explosiv hochspringen, Arme dynamisch mitschwingen.',
        'Weich auf dem Mittelfuß landen, Knie federn nach — direkt in die nächste Kniebeuge.',
        'Kontrolle vor Tempo — bei Formverlust Pause oder reguläre Kniebeuge nehmen.',
      ],
      tips: [
        'Nicht aus dem Vollbad-Stand starten — die Vorspannung im Squat erzeugt die Sprunghöhe.',
        'Hartes Aufkommen schadet den Gelenken; eine Matte oder weiche Schuhe helfen.',
      ],
    },
    en: {
      name: 'Jump Squats',
      summary:
        'Explosive squat with a vertical jump — speed-strength and lower-body power.',
      instructions: [
        'Lower into a regular squat.',
        'Drive up explosively from the bottom, arms swinging dynamically.',
        'Land soft on the mid-foot, knees absorbing — straight into the next squat.',
        'Control over speed — if form breaks, rest or drop to regular squats.',
      ],
      tips: [
        "Don't start from a tall stance — the pre-stretch at the bottom of the squat is what creates jump height.",
        'Hard landings are tough on joints; a mat or cushioned shoes help.',
      ],
    },
  },
  'legs.lunges': {
    de: {
      name: 'Ausfallschritte',
      summary:
        'Einbeiniges Beintraining im Schritt — Kraft, Balance und Symmetrie zwischen den Beinen.',
      instructions: [
        'Aufrecht stehen, einen großen Schritt nach vorn machen.',
        'Hinteres Knie kontrolliert Richtung Boden absenken, vorderes Knie über dem Fußgelenk.',
        'Beide Knie in etwa 90° gebeugt — vorderes Schienbein bleibt senkrecht.',
        'Über die vordere Ferse zurück in den aufrechten Stand drücken; Seite oder Bein wechseln.',
      ],
      tips: [
        'Aufrecht bleiben — der Oberkörper darf nicht nach vorn klappen.',
        'Variante: Rückwärts (Reverse Lunge) ist gelenkfreundlicher, Walking Lunges sind anspruchsvoller in Balance.',
      ],
    },
    en: {
      name: 'Lunges',
      summary:
        'Single-leg strength in a split stance — power, balance and side-to-side symmetry.',
      instructions: [
        'Stand tall, take a long step forward.',
        'Lower the back knee under control toward the floor, front knee stacked over the ankle.',
        'Both knees finish at roughly 90° — the front shin stays vertical.',
        'Drive through the front heel back to standing; switch sides or step.',
      ],
      tips: [
        'Stay upright — torso must not collapse forward.',
        'Variants: reverse lunges are easier on the knees, walking lunges add a balance demand.',
      ],
    },
  },
  'legs.squats': {
    de: {
      name: 'Kniebeugen',
      summary:
        'Königsübung für die Beine — Oberschenkel, Po und Rumpf in einer Bewegung.',
      instructions: [
        'Schulterbreiter Stand, Fußspitzen leicht nach außen.',
        'Hüfte nach hinten schicken, dann Knie über die Fußspitzen beugen — wie ein Hinsetzen auf einen unsichtbaren Stuhl.',
        'So tief gehen, wie Beweglichkeit und Hüfte es erlauben — Idealtiefe ist Oberschenkel parallel zum Boden oder tiefer.',
        'Aus den Fersen kraftvoll wieder nach oben drücken, Knie nicht durchstrecken.',
      ],
      tips: [
        'Knie folgen der Linie der Fußspitzen — nicht nach innen kippen.',
        'Beim Hochkommen Po aktiv anspannen, sonst übernimmt der Rücken zu viel.',
      ],
    },
    en: {
      name: 'Squats',
      summary:
        'King of leg exercises — quads, glutes and core in a single pattern.',
      instructions: [
        'Shoulder-width stance, toes turned slightly outward.',
        'Send the hips back, then bend the knees over the toes — like sitting on an invisible chair.',
        'Descend as deep as mobility and hips allow — ideally thighs parallel or below.',
        'Drive back up powerfully through the heels; do not lock the knees at the top.',
      ],
      tips: [
        'Track the knees over the toes — do not let them cave inward.',
        'Squeeze the glutes on the way up or the lower back ends up overworking.',
      ],
    },
  },
  'lunge.stepup': {
    de: {
      name: 'Step-ups',
      summary:
        'Auftreten auf eine Erhöhung — einbeinige Streckung mit hoher Alltagsrelevanz.',
      instructions: [
        'Vor einer stabilen Erhöhung (Bank, Stufe) stehen.',
        'Einen Fuß komplett auf die Erhöhung stellen — Ferse mittig auf der Auflagefläche.',
        'Über die Ferse hochdrücken, bis das hintere Bein in der Luft ist; oben kurz halten.',
        'Kontrolliert wieder absteigen, gleiches Bein oder Beinwechsel.',
      ],
      tips: [
        'Erhöhungshöhe wählen, sodass das vordere Knie ca. 90° beugt — sonst übernimmt der Schwung.',
        'Nicht mit dem hinteren Bein "abdrücken" — der Reiz kommt aus dem vorderen Bein.',
      ],
    },
    en: {
      name: 'Step-ups',
      summary:
        'Step up onto an elevation — single-leg extension with high carry-over to daily life.',
      instructions: [
        'Stand in front of a stable elevation (bench, step).',
        'Place one foot completely on the elevation — heel centred on the surface.',
        'Drive up through that heel until the back leg is airborne; pause briefly.',
        'Step back down under control, repeating on the same leg or alternating.',
      ],
      tips: [
        'Pick a height where the front knee bends to about 90° — otherwise momentum takes over.',
        "Don't push off the back leg — the stimulus has to come from the working (front) leg.",
      ],
    },
  },
  'mobility.catcow': {
    de: {
      name: 'Katze-Kuh',
      summary:
        'Wirbelsäulen-Mobilisation aus dem Vierfüßlerstand — wechselt zwischen Rundrücken und Hohlkreuz.',
      instructions: [
        'Im Vierfüßlerstand starten — Hände unter den Schultern, Knie unter der Hüfte.',
        'Einatmen, Kuh-Position: Bauch sinken lassen, Brust und Blick nach vorn-oben.',
        'Ausatmen, Katzen-Position: Wirbelsäule nach oben krümmen, Kinn zur Brust, Po einziehen.',
        'Im Atemrhythmus 8-12 Wiederholungen — keine schnellen, ruckartigen Bewegungen.',
      ],
      tips: [
        'Perfekt vor und nach langem Sitzen — mobilisiert die gesamte Wirbelsäule.',
        'Bewegung soll fließen, nicht ruckartig zwischen Endpositionen springen.',
      ],
    },
    en: {
      name: 'Cat-Cow',
      summary:
        'Spinal mobilisation in a quadruped position — alternates between rounded and arched back.',
      instructions: [
        'Start on hands and knees — hands under shoulders, knees under hips.',
        'Inhale, cow: drop the belly, lift the chest and gaze up and forward.',
        'Exhale, cat: round the spine to the ceiling, chin to chest, tail tucked.',
        'Move with the breath for 8-12 reps — no fast, jerky transitions.',
      ],
      tips: [
        'Perfect before and after long sitting — mobilises the whole spine.',
        'Movement should flow, not snap between end positions.',
      ],
    },
  },
  'mobility.dynamicwarmup': {
    de: {
      name: 'Dynamisches Aufwärmen',
      summary:
        'Bewegtes Aufwärmen vor dem Training — bereitet Gelenke, Muskeln und Nervensystem vor.',
      instructions: [
        '5-10 Minuten lockeres Bewegen (Joggen, Hampelmänner, Seilspringen) für Pulsanstieg.',
        'Anschließend gezielte Mobilisation der gleich beanspruchten Gelenke (Hüfte, Schulter, Sprunggelenk).',
        'Bewegungen mit großer ROM, aber ohne Endposition zu halten — Schwungübungen wie Beinpendel.',
        'Mit ein paar leichten Übungssätzen abschließen, bevor das Training beginnt.',
      ],
      tips: [
        'Vor Kraft-/Sprunglast immer dynamisch, kein statisches Dehnen — beeinträchtigt sonst die Leistung.',
        'Im Winter Aufwärmen verlängern; bei Hitze geht es schneller.',
      ],
    },
    en: {
      name: 'Dynamic Warm-up',
      summary:
        'Moving warm-up before training — primes joints, muscles and the nervous system.',
      instructions: [
        '5-10 minutes of easy movement (jog, jumping jacks, jump rope) to raise heart rate.',
        "Then targeted mobilisation of the joints you're about to load (hips, shoulders, ankles).",
        'Use large ranges of motion but no end-range holds — swings like leg pendulums.',
        'Finish with a few light working sets before the real session begins.',
      ],
      tips: [
        'Before strength or jumping always go dynamic, never static — static stretching dulls performance.',
        'Extend the warm-up in winter; shorten it in hot weather.',
      ],
    },
  },
  'mobility.foamrolling': {
    de: {
      name: 'Faszienrolle',
      summary:
        'Selbstmassage mit einer harten Schaumstoffrolle — löst Verspannungen und verbessert die Durchblutung.',
      instructions: [
        'Zielmuskel auf die Rolle legen, Körpergewicht kontrolliert darüber rollen.',
        'Langsam (2-3 cm pro Sekunde), auf empfindlichen Stellen 20-30 s pausieren.',
        'Gleichmäßig atmen — keine Atemstops bei Schmerz; ein "guter Schmerz" ist 5-6/10, mehr nicht.',
        'Jede Hauptmuskelgruppe 30-60 s, bei Bedarf länger.',
      ],
      tips: [
        'Vor dem Training kurz (1-2 Min. pro Stelle), nach dem Training länger und entspannender.',
        'Keine direkten Knochen oder Gelenke rollen — nur Muskelbäuche.',
      ],
    },
    en: {
      name: 'Foam Rolling',
      summary:
        'Self-massage on a foam roller — releases tension and improves circulation.',
      instructions: [
        'Place the target muscle on the roller, control your body weight over it.',
        'Roll slowly (2-3 cm per second), pause 20-30 s on tender spots.',
        'Breathe evenly — never hold the breath through discomfort; aim for 5-6/10 intensity, not more.',
        '30-60 s per major muscle group, longer when needed.',
      ],
      tips: [
        'Short (1-2 min per area) before training, longer and more relaxing afterwards.',
        "Don't roll directly on bones or joints — muscle bellies only.",
      ],
    },
  },
  'mobility.hipopener': {
    de: {
      name: 'Hüftöffner',
      summary:
        'Mobilisationsroutine für die Hüfte — wichtig für Sitzberufe und tiefe Kniebeugen.',
      instructions: [
        'Aus dem Vierfüßlerstand ein Bein vor sich nach außen klappen (90/90-Position).',
        'Hinteres Bein nach hinten strecken, beide Hüften gerade zum Boden ausgerichtet.',
        'Vorlehnen über das vordere Bein für mehr Dehnung im Po; sanftes Hin-und-Her.',
        'Wechseln zwischen Hüftöffner (Pigeon), Frosch und Schmetterling für volle Hüft-Mobilität.',
      ],
      tips: [
        'Lieber täglich 5 Minuten als einmal pro Woche 30.',
        'Atmung in die Dehnung — beim Ausatmen bewusst loslassen.',
      ],
    },
    en: {
      name: 'Hip Opener',
      summary:
        'Mobilisation routine for the hips — essential for desk-bound jobs and deep squats.',
      instructions: [
        'From all-fours bring one leg forward into the 90/90 position.',
        'Extend the back leg straight, both hip points square to the floor.',
        'Lean forward over the front leg for more glute stretch; gentle back-and-forth.',
        'Rotate through pigeon, frog and butterfly for full hip mobility.',
      ],
      tips: [
        '5 minutes daily beats 30 minutes once a week.',
        'Breathe into the stretch — release a little more on every exhale.',
      ],
    },
  },
  'mobility.stretching': {
    de: {
      name: 'Dehnen',
      summary:
        'Statisches Dehnen nach dem Training — verbessert langfristig den Bewegungsumfang.',
      instructions: [
        'Erst wenn Muskeln aufgewärmt sind (nach Training oder leichtem Aufwärmen).',
        'In jede Dehnposition langsam hineingleiten, bis ein leichtes Ziehen spürbar wird (kein Schmerz).',
        'Position 30-60 Sekunden ruhig halten, gleichmäßig atmen.',
        'Pro Sitzung 2-3 wiederholte Dehnungen pro Muskel — nicht aus dem Stand strecken.',
      ],
      tips: [
        'Statisches Dehnen vor harten Kraft-/Schnellkraftübungen kurz vermeiden (10-20 Min. Abstand).',
        'Beweglichkeit braucht Wochen — Geduld schlägt Intensität.',
      ],
    },
    en: {
      name: 'Stretching',
      summary:
        'Static stretching after training — improves range of motion long-term.',
      instructions: [
        'Only when muscles are warm (after training or light warm-up).',
        'Move into each stretch slowly until you feel a light pull (never pain).',
        'Hold each position 30-60 seconds quietly, breathing evenly.',
        '2-3 repeats per muscle per session — no cold-stretching from standing.',
      ],
      tips: [
        'Avoid static stretching right before heavy strength or speed work (leave 10-20 min).',
        'Flexibility takes weeks — patience beats intensity.',
      ],
    },
  },
  'mobility.yoga': {
    de: {
      name: 'Yoga',
      summary:
        'Bewegliche Praxis aus Haltung, Atem und Konzentration — Mobilität und Stress-Regulation.',
      instructions: [
        'Mit einer der vielen Stile beginnen (Hatha, Vinyasa, Yin) je nach Zielsetzung.',
        'Atem führt die Bewegung — Einatmen öffnet, Ausatmen vertieft.',
        'Jede Haltung sauber ausrichten, lieber kürzer halten als verkrampft enden.',
        'Mit Shavasana (Rückenlage) zum Abschluss — auch das gehört zur Praxis.',
      ],
      tips: [
        'Anfänger profitieren mehr von einer geführten Klasse (Studio oder Video) als von Improvisation.',
        '20-30 Minuten 3× pro Woche bringen schon spürbare Beweglichkeitsgewinne.',
      ],
    },
    en: {
      name: 'Yoga',
      summary:
        'Moving practice of posture, breath and focus — mobility and stress regulation in one.',
      instructions: [
        'Start with a style that fits your goal (Hatha, Vinyasa, Yin).',
        'Let the breath lead the movement — inhale to open, exhale to deepen.',
        'Align each pose cleanly; shorter and clean beats long and cramped.',
        "Finish with shavasana (lying still) — it's part of the practice.",
      ],
      tips: [
        'Beginners benefit more from a guided class (studio or video) than from improvising.',
        '20-30 minutes, 3× a week, already produces noticeable mobility gains.',
      ],
    },
  },
  'plank.standard': {
    de: {
      name: 'Plank',
      summary:
        'Isometrischer Stütz auf Unterarmen oder Händen — der Goldstandard für Rumpfstabilität.',
      instructions: [
        'Unterarme oder Handflächen schulterbreit am Boden, Ellenbogen direkt unter den Schultern.',
        'Körper bildet eine gerade Linie von Kopf bis Ferse, Po und Bauch aktiv anspannen.',
        'Schultern weg von den Ohren ziehen, Nacken lang lassen, Blick zwischen die Hände.',
        'Position halten — nicht durchhängen, kein Hohlkreuz, keine hochgeschobene Hüfte.',
      ],
      tips: [
        'Gleichmäßig weiteratmen — nicht die Luft anhalten.',
        'Anfänger: 3 × 20-30 s, Fortgeschrittene 3 × 60-90 s; bei Formverlust sofort abbrechen.',
      ],
    },
    en: {
      name: 'Plank',
      summary:
        'Isometric hold on forearms or hands — the gold standard for core stability.',
      instructions: [
        'Forearms or palms shoulder-width on the floor, elbows directly under the shoulders.',
        'Body forms a straight line from head to heels; actively brace glutes and abs.',
        'Pull the shoulders away from the ears, neck long, gaze between the hands.',
        'Hold the position — no sagging, no lower-back arch, no piked hips.',
      ],
      tips: [
        'Keep breathing evenly — do not hold your breath.',
        'Beginners: 3 × 20-30 s, advanced 3 × 60-90 s; stop the moment form breaks.',
      ],
    },
  },
  'pull.deadhang': {
    de: {
      name: 'Dead Hang',
      summary:
        'Passives Hängen an der Stange — Griffkraft, Schulterbeweglichkeit und entlastete Wirbelsäule.',
      instructions: [
        'An eine Klimmzugstange greifen, schulterbreit, Daumen außen (oder umfassend) — beide Füße in der Luft.',
        'Schultern aktiv nach unten und hinten ziehen — keine eingesunkene Schulterhaltung.',
        'Rumpf locker, aber kein Hohlkreuz — Beine ruhig, nicht schwingen.',
        'Solange halten wie sauber möglich, dann kontrolliert ablassen.',
      ],
      tips: [
        'Anfänger: 3 × 15-20 s; Fortgeschrittene 3 × 45-60 s — Endziel 1-2 Minuten am Stück.',
        'Bei sensiblen Schultern aktiver Hang (mit gezogenen Schulterblättern) statt passivem.',
      ],
    },
    en: {
      name: 'Dead Hang',
      summary:
        'Passive hang from a bar — grip strength, shoulder mobility and spinal decompression.',
      instructions: [
        'Grip a pull-up bar shoulder-width, thumbs outside the bar (or wrapped) — both feet off the floor.',
        'Keep the shoulders actively down and back — no shrugged, sunken position.',
        'Trunk relaxed but no lower-back arch — legs still, no swinging.',
        'Hold as long as form stays clean, then lower under control.',
      ],
      tips: [
        'Beginners: 3 × 15-20 s; advanced 3 × 45-60 s — long-term target 1-2 minutes straight.',
        'Sensitive shoulders? Use an active hang (scapulae depressed) instead of passive.',
      ],
    },
  },
  'pull.facepull': {
    de: {
      name: 'Face Pull',
      summary:
        'Hohes Ziehen mit Band oder Kabel — schult die rückwärtige Schulter und beugt Drücker-Imbalancen vor.',
      instructions: [
        'Band oder Kabelzug auf Augenhöhe befestigen, am Ende mit zwei Händen greifen.',
        'Aufrecht stehen, Arme nach vorn gestreckt; ein bis zwei Schritte zurückgehen, sodass Spannung entsteht.',
        'Ellenbogen hoch und nach außen Richtung Ohren ziehen, Daumen zeigen am Ende nach hinten.',
        'Pause am Endpunkt (1 s), dann kontrolliert zurück in Ausgangsposition.',
      ],
      tips: [
        'Schultern bleiben unten — kein Nach-Oben-Ziehen der Schulterblätter.',
        'Idealer Begleiter für jede Drück-Einheit; 15-25 Wiederholungen pro Satz.',
      ],
    },
    en: {
      name: 'Face Pull',
      summary:
        'High pull with a band or cable — trains the rear shoulders and counters pressing imbalances.',
      instructions: [
        'Anchor a band or cable at eye height, grip the ends with both hands.',
        'Stand tall with arms forward; step back one or two paces to put tension on the band.',
        'Pull the elbows up and out toward the ears, thumbs end pointing back.',
        'Pause briefly at the end (1 s), then return under control.',
      ],
      tips: [
        'Shoulders stay down — no shrugging the shoulder blades up.',
        'Ideal companion to any pressing session; 15-25 reps per set.',
      ],
    },
  },
  'pull.pullups': {
    de: {
      name: 'Klimmzüge',
      summary:
        'Vertikales Hochziehen am Reck — die Königsübung für Rücken, Bizeps und Griffkraft.',
      instructions: [
        'An eine Klimmzugstange hängen, Griff schulterbreit, Handrücken nach vorn (Standard) oder zu dir (Chin-up).',
        'Schulterblätter aktiv nach unten ziehen — kein Schulter-Hängen.',
        'Brust zur Stange ziehen, Ellenbogen nach unten und leicht nach hinten.',
        'Kontrolliert wieder in den vollen Hang ablassen — keine Schwungbewegung.',
      ],
      tips: [
        'Vorstufe: Negative Klimmzüge (hochspringen, langsam ablassen) oder mit Therapieband.',
        'Voller Bewegungsumfang — Kinn über die Stange, unten Ellenbogen ganz strecken.',
      ],
    },
    en: {
      name: 'Pull-ups',
      summary:
        'Vertical pull from a bar — the king of upper-body pulling for back, biceps and grip.',
      instructions: [
        'Hang from a pull-up bar, grip shoulder-width, palms facing forward (standard) or back (chin-up).',
        'Actively depress the shoulder blades — no shoulder shrug at the bottom.',
        'Pull the chest to the bar, elbows driving down and slightly back.',
        'Lower under control into a full hang — no kipping.',
      ],
      tips: [
        'Regression: negatives (jump up, lower slowly) or a band-assisted pull.',
        'Full range — chin over the bar at the top, elbows fully extended at the bottom.',
      ],
    },
  },
  'pull.rows': {
    de: {
      name: 'Ruderzug',
      summary:
        'Horizontales Ziehen — Komplement zum Drücken und Grundlage für gesunde Schulterhaltung.',
      instructions: [
        'Eigengewicht: unter einer niedrigen Stange oder TRX hängen, Körper als gerade Linie.',
        'Hantel: bei vorgebeugtem Stand mit geradem Rücken, Hantel auf Schienbein-Höhe.',
        'Mit den Schulterblättern starten — erst hinten zusammenziehen, dann Ellenbogen Richtung Hüfte.',
        'Kontrolliert zurück, bis die Schulterblätter wieder lang werden.',
      ],
      tips: [
        'Stange/Hantel zur unteren Rippe (Lat-Fokus) oder Brust (Mitte des Rückens) ziehen.',
        'Keine Schwungbewegung — Rumpf bleibt stabil, Bewegung kommt nur aus den Armen + oberen Rücken.',
      ],
    },
    en: {
      name: 'Rows',
      summary:
        'Horizontal pulling — counterpart to pressing and a key to healthy shoulder posture.',
      instructions: [
        'Bodyweight: hang under a low bar or TRX, body in a straight line.',
        'Weighted: hinge over with a flat back, weight near shin height.',
        'Initiate with the shoulder blades — retract first, then pull the elbows toward the hips.',
        'Lower back under control until the shoulder blades feel long again.',
      ],
      tips: [
        'Pull to the lower ribs to bias the lats; pull to the chest for the mid-back.',
        'No kipping — the trunk stays still, only the arms and upper back move.',
      ],
    },
  },
  'push.benchdips': {
    de: {
      name: 'Bankdips',
      summary:
        'Trizeps-Dips mit Hand-Auflage auf einer Bank — einfache Einstiegsvariante.',
      instructions: [
        'Mit dem Rücken zu einer Bank stehen, Hände schulterbreit auf der Bankkante.',
        'Po vor die Bank schieben, Beine gestreckt oder gebeugt vorne abstellen.',
        'Ellenbogen kontrolliert auf etwa 90° beugen, Po sinkt direkt nach unten (nicht nach vorn).',
        'Mit dem Trizeps wieder hochdrücken, oben nicht durchstrecken.',
      ],
      tips: [
        'Schultergelenk schonen — nicht zu tief gehen, wenn es zwickt.',
        'Schwerer machen mit gestreckten Beinen, Füßen auf einer zweiten Bank oder Zusatzgewicht auf dem Oberschenkel.',
      ],
    },
    en: {
      name: 'Bench Dips',
      summary: 'Triceps dips with hands on a bench — accessible entry variant.',
      instructions: [
        'Stand with your back to a bench, hands shoulder-width on the bench edge.',
        'Slide the hips forward off the bench, legs extended or bent in front.',
        'Bend the elbows to about 90° under control, hips sinking straight down (not forward).',
        'Press back up with the triceps, do not lock out the elbows.',
      ],
      tips: [
        "Protect the shoulders — don't go deeper than feels good.",
        'Make it harder with straight legs, feet on a second bench, or weight on the lap.',
      ],
    },
  },
  'push.dips': {
    de: {
      name: 'Dips',
      summary:
        'Vertikales Drücken am Barren oder an Ringen — Brust, Trizeps und Schultern in einem Zug.',
      instructions: [
        'An zwei parallelen Stangen aufstützen, Arme gestreckt, Beine frei.',
        'Schulterblätter aktiv unten halten — nicht in die Schultern hängen.',
        'Körper kontrolliert absenken, Ellenbogen leicht nach hinten, bis Oberarm parallel zum Boden ist.',
        'Kraftvoll wieder hochdrücken, oben nicht durchstrecken.',
      ],
      tips: [
        'Brust-Fokus durch leichten Vorlehnen, Trizeps-Fokus durch aufrechten Oberkörper.',
        'Anfänger: zuerst Bankdips, dann negative Dips (nur die Absenkphase), dann volle Dips.',
      ],
    },
    en: {
      name: 'Dips',
      summary:
        'Vertical pressing on parallel bars or rings — chest, triceps and shoulders in one move.',
      instructions: [
        'Support on two parallel bars, arms extended, legs free.',
        'Actively depress the shoulder blades — do not hang in the joints.',
        'Lower the body under control, elbows tracking slightly back, until upper arm is parallel.',
        'Press back up powerfully, do not lock the elbows.',
      ],
      tips: [
        'Lean slightly forward to bias the chest; stay upright to bias the triceps.',
        'Beginners: start with bench dips, then negative dips (eccentric only), then full dips.',
      ],
    },
  },
  'push.handstandhold': {
    de: {
      name: 'Handstand-Hold',
      summary:
        'Statischer Handstand an einer Wand oder frei — Schulterkraft, Stabilität und Körperspannung.',
      instructions: [
        'Vor einer freien Wand niederknien, Hände schulterbreit, Fingerspitzen ca. eine Handflächenbreite von der Wand entfernt.',
        'Ein Bein nach oben kicken, das andere folgt — Fersen lehnen sich an die Wand.',
        'Körper als gerade Linie halten — Hüfte und Brustkorb über den Händen, Po angespannt.',
        'Kontrolliert ablassen, bevor die Schultern ermüden.',
      ],
      tips: [
        'Anfänger: Pike-Liegestütze und Wall Walks vorher beherrschen, dann erst halten lernen.',
        'Schultern aktiv "in die Ohren" pressen — keine eingesunkene Position.',
      ],
    },
    en: {
      name: 'Handstand Hold',
      summary:
        'Static handstand against a wall or free — shoulder strength, stability and full-body tension.',
      instructions: [
        "Kneel in front of an open wall, hands shoulder-width, fingertips about a hand's width from the wall.",
        'Kick one leg up, the other follows — heels rest lightly against the wall.',
        'Hold the body as a straight line — hips and chest stacked over the hands, glutes braced.',
        'Lower back down before the shoulders fatigue.',
      ],
      tips: [
        'Beginners: build pike push-ups and wall walks first, then start practising the hold.',
        'Press the shoulders actively "into the ears" — no sunken position.',
      ],
    },
  },
  'squat.boxjump': {
    de: {
      name: 'Box Jumps',
      summary:
        'Sprung auf eine Erhöhung — Schnellkraft, Koordination und Selbstvertrauen.',
      instructions: [
        'Vor einer stabilen Erhöhung (Box, Bank, niedriger Hocker) stehen.',
        'In eine Vorhocke gehen, Arme nach hinten schwingen.',
        'Aus der Hocke explosiv abspringen, Arme nach vorn.',
        'Mit beiden Füßen weich auf der Box landen, Knie federn — danach kontrolliert wieder absteigen.',
      ],
      tips: [
        'Wähle eine Höhe, die du sicher schaffst — Verletzungen passieren meist beim zu Hohen.',
        'Nicht herunterspringen — die Belastung beim Landen ist hoch; immer absteigen.',
      ],
    },
    en: {
      name: 'Box Jumps',
      summary:
        'Jump onto a sturdy elevation — speed-strength, coordination and confidence.',
      instructions: [
        'Stand in front of a stable box (or bench, low stool).',
        'Drop into a quarter-squat, arms swinging back.',
        'Drive up explosively from the squat, arms swinging forward.',
        "Land soft on both feet on the box, knees absorbing — then step (don't jump) back down.",
      ],
      tips: [
        'Pick a height you can clear safely — most box-jump injuries come from going too high.',
        'Step down between reps — landing repeatedly from height is hard on knees and Achilles.',
      ],
    },
  },
  'squat.wallsit': {
    de: {
      name: 'Wandsitz',
      summary:
        'Isometrische Kniebeuge mit dem Rücken an der Wand — Brennen pur in den Oberschenkeln.',
      instructions: [
        'Mit dem Rücken flach an einer Wand stehen, Füße etwa hüftbreit, eine Schrittweite vor der Wand.',
        'Den Rücken die Wand entlang nach unten gleiten lassen, bis die Knie im 90°-Winkel sind.',
        'Oberschenkel parallel zum Boden, Knie über den Knöcheln.',
        'Position halten — Druck gleichmäßig auf beide Fersen, Bauch leicht aktiv.',
      ],
      tips: [
        'Anfänger: 3 × 20-30 s; Fortgeschrittene 3 × 60-90 s.',
        'Bei Knieschmerzen die Hüfte etwas höher halten — 90° muss nicht erzwungen werden.',
      ],
    },
    en: {
      name: 'Wall Sit',
      summary: 'Isometric squat with the back on a wall — pure quad burn.',
      instructions: [
        'Stand with the back flat against a wall, feet about hip-width, one stride forward.',
        'Slide down the wall until the knees are bent to 90°.',
        'Thighs parallel to the floor, knees stacked over the ankles.',
        'Hold the position — pressure even on both heels, abs lightly engaged.',
      ],
      tips: [
        'Beginners: 3 × 20-30 s; advanced 3 × 60-90 s.',
        'If knees complain, keep the hips slightly higher — 90° is not mandatory.',
      ],
    },
  },
};
