// AUTO-GENERATED by tools/src/generate-content.mjs — do not edit directly.
// Source files: content/blog/<folder>/<lang>.md and content/wiki/pushup-types/<id>.<lang>.md
// (any lowercase locale code is accepted, not just de/en).
// Run `pnpm nx run tools:generate-content` to regenerate (also runs automatically
// before `pnpm nx run web:build`).

export interface PushupTypeContent {
  readonly name: string;
  readonly summary: string;
  readonly instructions: ReadonlyArray<string>;
  readonly tips: ReadonlyArray<string>;
}

/**
 * Translatable wiki copy for push-up types. Keys are PushupTypeId
 * strings; values are per-locale content blocks. Types not represented
 * here fall back to the legacy parallel `*En` fields on PUSHUP_TYPES.
 */
export const PUSHUP_TYPE_CONTENT: Readonly<
  Record<string, Readonly<Record<string, PushupTypeContent>>>
> = {
  "archer": {
    "de": {
      "name": "Archer-Liegestütze",
      "summary": "Asymmetrische Liegestütze: ein Arm beugt, der andere bleibt gestreckt — Vorstufe zur einarmigen Liegestütze.",
      "instructions": [
        "Hände deutlich breiter als schulterbreit, Finger leicht nach außen.",
        "Beim Absenken zur einen Seite verlagern: ein Arm beugt, der andere bleibt fast gestreckt.",
        "Gestreckter Arm dient als Stütze, Hauptlast liegt auf dem beugenden Arm.",
        "Kontrolliert hochdrücken, dabei wieder zur Mitte verlagern, dann zur anderen Seite.",
        "Wiederholungen pro Seite zählen — die Liste meint typischerweise pro Arm."
      ],
      "tips": [
        "Tempo 3-1-1 (3 s runter, 1 s halten, 1 s hoch) baut spürbar mehr Kraft auf."
      ]
    },
    "el": {
      "name": "Πιέσεις Archer",
      "summary": "Ασύμμετρες πιέσεις: ο ένας βραχίονας λυγίζει ενώ ο άλλος μένει τεντωμένος — ενδιάμεσο βήμα προς τις πιέσεις με έναν βραχίονα.",
      "instructions": [
        "Χέρια αισθητά πιο φαρδιά από τους ώμους, δάχτυλα ελαφρώς προς τα έξω.",
        "Στην κατάβαση μετατόπισε το βάρος προς τη μία πλευρά: ο ένας βραχίονας λυγίζει, ο άλλος μένει σχεδόν ίσιος.",
        "Ο τεντωμένος βραχίονας λειτουργεί σαν στήριγμα· το μεγαλύτερο φορτίο πέφτει στον βραχίονα που λυγίζει.",
        "Σπρώξε ελεγχόμενα προς τα πάνω, επίστρεψε στο κέντρο και μετατοπίσου στην άλλη πλευρά.",
        "Μέτρα τις επαναλήψεις ανά πλευρά — το πρόγραμμα συνήθως αναφέρει τον αριθμό ανά βραχίονα."
      ],
      "tips": [
        "Ρυθμός 3-1-1 (3 δευτ. κάτω, 1 δευτ. κράτημα, 1 δευτ. πάνω) χτίζει αισθητά περισσότερη δύναμη."
      ]
    },
    "en": {
      "name": "Archer push-up",
      "summary": "Asymmetric push-up: one arm bends while the other stays extended — a stepping stone to the one-arm push-up.",
      "instructions": [
        "Hands set noticeably wider than shoulders, fingers angled slightly out.",
        "On the descent shift to one side: one arm bends, the other stays nearly straight.",
        "The straight arm acts as support; most of the load lives on the bending arm.",
        "Press back up under control, return to centre, then shift to the other side.",
        "Count reps per side — the plan usually lists the per-arm number."
      ],
      "tips": [
        "Tempo 3-1-1 (3 s down, 1 s hold, 1 s up) builds noticeably more strength."
      ]
    },
    "es": {
      "name": "Flexión de arquero",
      "summary": "Flexión asimétrica: un brazo se dobla mientras el otro permanece extendido — un escalón previo a la flexión de un solo brazo.",
      "instructions": [
        "Manos notablemente más separadas que los hombros, dedos ligeramente hacia fuera.",
        "En el descenso, desplázate hacia un lado: un brazo se dobla, el otro permanece casi recto.",
        "El brazo recto actúa como apoyo; la mayor parte de la carga recae en el brazo que se dobla.",
        "Empuja hacia arriba de forma controlada, vuelve al centro y luego desplázate al otro lado.",
        "Cuenta las repeticiones por lado — el plan normalmente indica el número por brazo."
      ],
      "tips": [
        "El tempo 3-1-1 (3 s abajo, 1 s pausa, 1 s arriba) genera notablemente más fuerza."
      ]
    },
    "fr": {
      "name": "Pompe archer",
      "summary": "Pompe asymétrique : un bras fléchit pendant que l'autre reste tendu — un tremplin vers la pompe à un bras.",
      "instructions": [
        "Placez les mains nettement plus larges que les épaules, doigts légèrement orientés vers l'extérieur.",
        "À la descente, déplacez le poids d'un côté : un bras fléchit, l'autre reste presque droit.",
        "Le bras tendu fait office d'appui ; la majorité de la charge repose sur le bras qui fléchit.",
        "Repoussez de façon contrôlée, revenez au centre, puis déplacez-vous de l'autre côté.",
        "Comptez les répétitions par côté — le plan indique généralement le nombre par bras."
      ],
      "tips": [
        "Un tempo 3-1-1 (3 s en bas, 1 s de maintien, 1 s en haut) développe nettement plus de force."
      ]
    },
    "it": {
      "name": "Piegamento arciere",
      "summary": "Piegamento asimmetrico: un braccio si piega mentre l'altro rimane esteso — un passaggio intermedio verso il piegamento a un braccio.",
      "instructions": [
        "Mani posizionate notevolmente più larghe delle spalle, dita leggermente ruotate verso l'esterno.",
        "Durante la discesa, sposta il peso su un lato: un braccio si piega, l'altro rimane quasi disteso.",
        "Il braccio disteso funge da supporto; la maggior parte del carico è sul braccio che si piega.",
        "Risali in modo controllato, torna al centro, poi sposta il peso sull'altro lato.",
        "Conta le ripetizioni per lato — il piano di solito indica il numero per braccio."
      ],
      "tips": [
        "Un tempo 3-1-1 (3 s discesa, 1 s pausa, 1 s salita) sviluppa la forza in modo notevolmente più efficace."
      ]
    },
    "nl": {
      "name": "Archer-opdruk",
      "summary": "Asymmetrische opdruk: één arm buigt terwijl de andere gestrekt blijft — een opstap naar de eénarmige opdruk.",
      "instructions": [
        "Handen duidelijk breder dan schouderbreedte, vingers licht naar buiten gericht.",
        "Verschuif bij het zakken naar één kant: één arm buigt, de andere blijft bijna recht.",
        "De gestrekte arm fungeert als steun; de meeste belasting ligt op de buigende arm.",
        "Druk gecontroleerd terug omhoog, keer terug naar het midden, verschuif dan naar de andere kant.",
        "Tel herhalingen per kant — het plan vermeldt doorgaans het per-arm aantal."
      ],
      "tips": [
        "Tempo 3-1-1 (3 s naar beneden, 1 s vasthouden, 1 s omhoog) bouwt merkbaar meer kracht op."
      ]
    },
    "no": {
      "name": "Archer armhevning",
      "summary": "Asymmetrisk armhevning der en arm bøyes mens den andre forblir strukket – en springbrett til enarmede armhevninger.",
      "instructions": [
        "Hendene plasseres merkbart bredere enn skuldrene, fingrene vinklet litt utover.",
        "Skift til den ene siden under nedstigningen: en arm bøyes, den andre forblir nesten rett.",
        "Den rette armen fungerer som støtte; det meste av belastningen ligger på den bøyde armen.",
        "Press oppover med kontroll, gå tilbake til midtposisjonen, og skift til den andre siden.",
        "Tell repetisjoner per side – planen lister vanligvis antallet per arm."
      ],
      "tips": [
        "Tempo 3-1-1 (3 s ned, 1 s hold, 1 s opp) bygger merkbart mer styrke."
      ]
    },
    "zh": {
      "name": "弓箭手俯卧撑",
      "summary": "非对称俯卧撑：一臂弯曲，另一臂保持伸展——通往单臂俯卧撑的垫脚石。",
      "instructions": [
        "双手位置明显宽于肩膀，手指略微向外倾斜。",
        "下降时向一侧倾斜：一臂弯曲，另一臂几乎保持笔直。",
        "笔直的那一臂起支撑作用，大部分负荷落在弯曲的那一臂上。",
        "控制速度向上按压，回到中间位置，然后向另一侧倾斜。",
        "每一侧单独计次——计划通常列出每臂的次数。"
      ],
      "tips": [
        "节奏3-1-1（下降3秒，停顿1秒，上升1秒）能明显增加力量。"
      ]
    }
  },
  "decline": {
    "de": {
      "name": "Decline-Liegestütze (Füße erhöht)",
      "summary": "Füße auf einer Erhöhung, Hände am Boden — zusätzliche Belastung für die obere Brust und Schultern.",
      "instructions": [
        "Füße auf einer stabilen Erhöhung (Bank, Stuhl, Stufe).",
        "Hände schulterbreit am Boden, gerade Linie von Kopf bis Ferse halten.",
        "Brust kontrolliert zum Boden senken, dabei Bauchspannung halten.",
        "Kraftvoll hochdrücken — je höher die Füße, desto mehr Schulteranteil."
      ],
      "tips": [
        "Nicht ins Hohlkreuz fallen — Bauch und Po aktiv anspannen, besonders mit hohen Füßen."
      ]
    },
    "el": {
      "name": "Πιέσεις με ανυψωμένα πόδια (Decline)",
      "summary": "Πόδια σε ύψωμα, χέρια στο πάτωμα — επιπλέον φορτίο στο πάνω στήθος και τους ώμους.",
      "instructions": [
        "Πόδια πάνω σε σταθερό ύψωμα (πάγκος, καρέκλα, σκαλοπάτι).",
        "Χέρια στο πλάτος των ώμων στο πάτωμα, κράτα ίσια γραμμή από το κεφάλι ως τις φτέρνες.",
        "Κατέβασε ελεγχόμενα το στήθος, διατηρώντας ενεργή την κοιλιά.",
        "Σπρώξε δυνατά προς τα πάνω — όσο πιο ψηλά τα πόδια, τόσο περισσότερη συμμετοχή των ώμων."
      ],
      "tips": [
        "Μην αφήνεις τη μέση να λυγίσει προς τα μέσα — σφίξε ενεργά κοιλιακούς και γλουτούς, ιδίως όταν τα πόδια είναι ψηλά."
      ]
    },
    "en": {
      "name": "Decline push-up (feet elevated)",
      "summary": "Feet on an elevation, hands on the floor — extra load on the upper chest and shoulders.",
      "instructions": [
        "Feet on a stable elevation (bench, chair, step).",
        "Hands shoulder-width on the floor, keep a straight line from head to heels.",
        "Lower the chest under control, keep the abs braced.",
        "Press up powerfully — the higher the feet, the more shoulder involvement."
      ],
      "tips": [
        "Do not let the lower back arch — actively brace abs and glutes, especially with high feet."
      ]
    },
    "es": {
      "name": "Flexión declinada (pies elevados)",
      "summary": "Pies sobre una elevación, manos en el suelo — mayor carga sobre el pecho superior y los hombros.",
      "instructions": [
        "Pies sobre una elevación estable (banco, silla, escalón).",
        "Manos a la anchura de los hombros en el suelo, mantén una línea recta de la cabeza a los talones.",
        "Baja el pecho de forma controlada, mantén los abdominales activos.",
        "Empuja hacia arriba con potencia — cuanto más altos los pies, mayor implicación de los hombros."
      ],
      "tips": [
        "No dejes que la zona lumbar se curve — activa activamente los abdominales y los glúteos, especialmente con los pies muy elevados."
      ]
    },
    "fr": {
      "name": "Pompe déclinée (pieds surélevés)",
      "summary": "Pieds sur une élévation, mains au sol — charge supplémentaire sur les pectoraux supérieurs et les épaules.",
      "instructions": [
        "Placez les pieds sur une élévation stable (banc, chaise, marche).",
        "Mains à largeur d'épaules au sol, gardez une ligne droite de la tête aux talons.",
        "Descendez la poitrine de façon contrôlée, abdominaux gainés.",
        "Poussez puissamment vers le haut — plus les pieds sont hauts, plus les épaules travaillent."
      ],
      "tips": [
        "Ne laissez pas le bas du dos se creuser — gainez activement abdominaux et fessiers, surtout avec les pieds hauts."
      ]
    },
    "it": {
      "name": "Piegamento declinato (piedi in elevazione)",
      "summary": "Piedi su un rialzo, mani a terra — carico extra sul petto superiore e sulle spalle.",
      "instructions": [
        "Piedi su una superficie stabile (panca, sedia, scalino).",
        "Mani alla larghezza delle spalle a terra, mantieni una linea retta dalla testa ai talloni.",
        "Abbassa il petto in modo controllato, tenendo gli addominali in tensione.",
        "Spingi su con forza — più i piedi sono alti, maggiore è il coinvolgimento delle spalle."
      ],
      "tips": [
        "Non lasciare che la zona lombare si inarcherebbe — tieni addominali e glutei attivi, soprattutto con i piedi molto alti."
      ]
    },
    "nl": {
      "name": "Decline-opdruk (voeten verhoogd)",
      "summary": "Voeten op een verhoging, handen op de vloer — extra belasting op de bovenborst en schouders.",
      "instructions": [
        "Voeten op een stabiele verhoging (bank, stoel, opstap).",
        "Handen schouderbreedte op de vloer, houd een rechte lijn van hoofd tot hielen.",
        "Laat de borst gecontroleerd zakken, houd buikspieren aangespannen.",
        "Druk krachtig omhoog — hoe hoger de voeten, hoe meer schouderbetrokkenheid."
      ],
      "tips": [
        "Laat de lage rug niet hollen — span buik en bilspieren actief aan, zeker bij hoge voeten."
      ]
    },
    "no": {
      "name": "Decline armhevning (føttene høyt)",
      "summary": "Føttene på en forhøyning, hendene på gulvet – ekstra belastning på øvre bryst og skuldre.",
      "instructions": [
        "Plasser føttene på en stabil forhøyning (benk, stol, trinn).",
        "Hendene skulderbredde fra hverandre på gulvet, hold en rett linje fra hode til hæl.",
        "Senk brystet med kontroll, hold magen strammet.",
        "Press oppover kraftig – jo høyere føttene, desto mer involvering av skulderne."
      ],
      "tips": [
        "Ikke la nedre del av ryggen bukte – stram aktivt magen og setemusklene, spesielt ved høye føtter."
      ]
    },
    "zh": {
      "name": "下斜俯卧撑（脚部抬高）",
      "summary": "脚踩在抬高的物体上，双手在地面上——增加胸部上部和肩膀的负荷。",
      "instructions": [
        "脚踩在稳定的抬高物体上（长凳、椅子、台阶）。",
        "双手与肩同宽放在地面上，从头到脚跟保持一直线。",
        "控制速度下降胸部，保持腹部收紧。",
        "有力地向上按压——脚抬得越高，肩膀参与度越大。"
      ],
      "tips": [
        "不要让下背部拱起——特别是脚抬高时，要积极收紧腹部和臀部。"
      ]
    }
  },
  "diamond": {
    "de": {
      "name": "Diamant-Liegestütze",
      "summary": "Hände bilden ein Dreieck unter der Brust — maximale Trizeps-Aktivierung.",
      "instructions": [
        "Daumen und Zeigefinger berühren sich, bilden ein \"Diamant\"-Dreieck.",
        "Hände direkt unter der unteren Brust, nicht zu weit Richtung Bauch.",
        "Ellenbogen eng am Körper halten, nach hinten zeigend.",
        "Brust zum Diamant absenken, dann gerade hochdrücken."
      ],
      "tips": [
        "Anfänger: an Knie-Diamant gewöhnen, bevor die volle Variante gemacht wird."
      ]
    },
    "el": {
      "name": "Πιέσεις διαμάντι",
      "summary": "Τα χέρια σχηματίζουν τρίγωνο κάτω από το στήθος — μέγιστη ενεργοποίηση τρικέφαλου.",
      "instructions": [
        "Οι αντίχειρες και οι δείκτες ενώνονται και σχηματίζουν ένα τρίγωνο «διαμάντι».",
        "Χέρια ακριβώς κάτω από το κάτω μέρος του στήθους, όχι πολύ χαμηλά προς την κοιλιά.",
        "Κράτα τους αγκώνες κοντά στο σώμα, να δείχνουν προς τα πίσω.",
        "Κατέβασε το στήθος μέχρι το διαμάντι και σπρώξε ίσια προς τα πάνω."
      ],
      "tips": [
        "Αρχάριοι: συνηθίστε στις πιέσεις διαμάντι από τα γόνατα προτού επιχειρήσετε την πλήρη εκδοχή."
      ]
    },
    "en": {
      "name": "Diamond push-up",
      "summary": "Hands form a triangle under the chest — maximum triceps engagement.",
      "instructions": [
        "Thumbs and index fingers touch, forming a \"diamond\" triangle.",
        "Hands directly under the lower chest, not too far down toward the belly.",
        "Keep the elbows close to the torso, pointing back.",
        "Lower the chest to the diamond, then press straight up."
      ],
      "tips": [
        "Beginners: get comfortable with knee-diamonds before attempting the full version."
      ]
    },
    "es": {
      "name": "Flexión de diamante",
      "summary": "Las manos forman un triángulo bajo el pecho — máxima activación del tríceps.",
      "instructions": [
        "Los pulgares y los índices se tocan formando un triángulo en \"diamante\".",
        "Manos directamente bajo el pecho inferior, no demasiado abajo hacia el abdomen.",
        "Mantén los codos cerca del torso, apuntando hacia atrás.",
        "Baja el pecho hasta el diamante y luego empuja recto hacia arriba."
      ],
      "tips": [
        "Principiantes: practica primero los diamantes de rodillas antes de intentar la versión completa."
      ]
    },
    "fr": {
      "name": "Pompe diamant",
      "summary": "Les mains forment un triangle sous la poitrine — engagement maximal des triceps.",
      "instructions": [
        "Les pouces et les index se touchent en formant un triangle en « diamant ».",
        "Mains directement sous la partie inférieure de la poitrine, pas trop bas vers le ventre.",
        "Gardez les coudes proches du torse, orientés vers l'arrière.",
        "Descendez la poitrine jusqu'au diamant, puis poussez droit vers le haut."
      ],
      "tips": [
        "Débutants : maîtrisez d'abord les pompes diamant sur les genoux avant de tenter la version complète."
      ]
    },
    "it": {
      "name": "Piegamento a diamante",
      "summary": "Le mani formano un triangolo sotto il petto — massimo coinvolgimento dei tricipiti.",
      "instructions": [
        "Pollici e indici si toccano, formando un triangolo a \"diamante\".",
        "Mani direttamente sotto il petto inferiore, non troppo in basso verso l'addome.",
        "Tieni i gomiti vicini al busto, puntati verso dietro.",
        "Abbassa il petto fino al diamante, poi spingi direttamente verso l'alto."
      ],
      "tips": [
        "Principianti: familiarizzate con il diamante sulle ginocchia prima di tentare la versione completa."
      ]
    },
    "nl": {
      "name": "Diamantopdruk",
      "summary": "Handen vormen een driehoek onder de borst — maximale tricepsbetrokkenheid.",
      "instructions": [
        "Duimen en wijsvingers raken elkaar en vormen een \"diamant\"-driehoek.",
        "Handen direct onder de onderborst, niet te ver naar de buik.",
        "Houd de ellebogen dicht bij de romp, naar achteren gericht.",
        "Laat de borst zakken naar de diamant, druk dan recht omhoog."
      ],
      "tips": [
        "Beginners: wen eerst aan knie-diamantopdrukken voordat je de volledige versie probeert."
      ]
    },
    "no": {
      "name": "Diamond armhevning",
      "summary": "Hendene danner en trekant under brystet – maksimal triceps-engasjement.",
      "instructions": [
        "Tomler og pekefingre berører hverandre og danner en \"diamant\"-trekant.",
        "Hendene direkte under det nedre brystet, ikke for langt ned mot magen.",
        "Hold albueleddet tett inntil kroppen, rettet bakover.",
        "Senk brystet ned til diamanten, og press deretter rett oppover."
      ],
      "tips": [
        "Nybegynnere: bli komfortabel med kne-diamant før du prøver fullversjonen."
      ]
    },
    "zh": {
      "name": "钻石俯卧撑",
      "summary": "双手形成胸部下方的三角形——最大化三头肌参与。",
      "instructions": [
        "拇指和食指相接触，形成\"钻石\"三角形。",
        "双手位于胸部下方正下方，不要太靠下。",
        "保持肘部贴近躯干，指向身体后方。",
        "下降胸部至钻石位置，然后直接向上按压。"
      ],
      "tips": [
        "初学者：先做跪姿钻石俯卧撑，熟悉后再尝试完整版本。"
      ]
    }
  },
  "incline": {
    "de": {
      "name": "Incline-Liegestütze (Hände erhöht)",
      "summary": "Hände auf einer Bank, Tisch oder Wand — reduziert das Körpergewicht auf den Armen.",
      "instructions": [
        "Hände auf einer stabilen Erhöhung (Bank, Tisch, Treppenstufe).",
        "Füße am Boden, Körper bildet eine gerade Linie.",
        "Brust kontrolliert zur Erhöhung absenken, dann hochdrücken.",
        "Je niedriger die Erhöhung, desto schwieriger die Übung."
      ],
      "tips": [
        "Schrittweise tiefer gehen, sobald 3×10 sauber gelingen."
      ]
    },
    "el": {
      "name": "Πιέσεις με ανυψωμένα χέρια (Incline)",
      "summary": "Χέρια σε πάγκο, τραπέζι ή τοίχο — μειώνει το βάρος που σηκώνουν τα χέρια.",
      "instructions": [
        "Τοποθέτησε τα χέρια σε σταθερό ύψωμα (πάγκος, τραπέζι, σκαλοπάτι).",
        "Πόδια στο πάτωμα, σώμα σε ίσια γραμμή.",
        "Κατέβασε ελεγχόμενα το στήθος ως το ύψωμα και μετά σπρώξε προς τα πάνω.",
        "Όσο πιο χαμηλό το ύψωμα, τόσο πιο δύσκολη η άσκηση."
      ],
      "tips": [
        "Κατέβασε το ύψωμα μόλις καταφέρεις 3×10 καθαρές επαναλήψεις."
      ]
    },
    "en": {
      "name": "Incline push-up (hands elevated)",
      "summary": "Hands on a bench, table or wall — reduces the load on the arms.",
      "instructions": [
        "Place the hands on a stable elevation (bench, table, stair).",
        "Feet on the floor, body in a straight line.",
        "Lower the chest under control to the elevation, then press up.",
        "The lower the elevation, the harder the exercise."
      ],
      "tips": [
        "Step the elevation down once 3×10 reps feel clean."
      ]
    },
    "es": {
      "name": "Flexión inclinada (manos elevadas)",
      "summary": "Manos sobre un banco, mesa o pared — reduce la carga sobre los brazos.",
      "instructions": [
        "Coloca las manos sobre una elevación estable (banco, mesa, escalón).",
        "Pies en el suelo, cuerpo en línea recta.",
        "Baja el pecho de forma controlada hasta la elevación y luego empuja hacia arriba.",
        "Cuanto más baja la elevación, más difícil el ejercicio."
      ],
      "tips": [
        "Baja la elevación una vez que 3×10 repeticiones se sientan limpias."
      ]
    },
    "fr": {
      "name": "Pompe inclinée (mains surélevées)",
      "summary": "Mains sur un banc, une table ou un mur — réduit la charge sur les bras.",
      "instructions": [
        "Placez les mains sur une élévation stable (banc, table, marche).",
        "Pieds au sol, corps en ligne droite.",
        "Descendez la poitrine de façon contrôlée jusqu'à l'élévation, puis poussez vers le haut.",
        "Plus l'élévation est basse, plus l'exercice est difficile."
      ],
      "tips": [
        "Abaissez l'élévation dès que 3×10 répétitions semblent propres."
      ]
    },
    "it": {
      "name": "Piegamento inclinato (mani in elevazione)",
      "summary": "Mani su una panca, tavolo o parete — riduce il carico sulle braccia.",
      "instructions": [
        "Posiziona le mani su una superficie stabile (panca, tavolo, scalino).",
        "Piedi a terra, corpo in linea retta.",
        "Abbassa il petto in modo controllato fino alla superficie, poi spingi su.",
        "Più bassa è la superficie, più difficile è l'esercizio."
      ],
      "tips": [
        "Abbassa l'altezza della superficie una volta che 3×10 ripetizioni risultano pulite e controllate."
      ]
    },
    "nl": {
      "name": "Incline-opdruk (handen verhoogd)",
      "summary": "Handen op een bank, tafel of muur — vermindert de belasting op de armen.",
      "instructions": [
        "Plaats de handen op een stabiele verhoging (bank, tafel, trap).",
        "Voeten op de vloer, lichaam in een rechte lijn.",
        "Laat de borst gecontroleerd zakken naar de verhoging, druk dan omhoog.",
        "Hoe lager de verhoging, hoe zwaarder de oefening."
      ],
      "tips": [
        "Ga een stap lager met de verhoging zodra 3×10 herhalingen vlot aanvoelen."
      ]
    },
    "no": {
      "name": "Incline armhevning (hendene høyt)",
      "summary": "Hendene på en benk, bord eller vegg – reduserer belastningen på armene.",
      "instructions": [
        "Plasser hendene på en stabil forhøyning (benk, bord, trapp).",
        "Føttene på gulvet, kroppen i en rett linje.",
        "Senk brystet med kontroll ned til forhøyningen, og press deretter oppover.",
        "Jo lavere forhøyningen, desto vanskeligere øvelsen."
      ],
      "tips": [
        "Senk forhøyningen når 3×10 repetisjoner føles rene og kontrollerte."
      ]
    },
    "zh": {
      "name": "上斜俯卧撑（双手抬高）",
      "summary": "双手放在长凳、桌子或墙上——减少对手臂的负荷。",
      "instructions": [
        "双手放在稳定的抬高物体上（长凳、桌子、楼梯）。",
        "脚踩地面，身体保持一直线。",
        "控制速度下降胸部至抬高物体，然后向上按压。",
        "抬高物体越低，动作难度越大。"
      ],
      "tips": [
        "当3组10次动作都能干净完成后，降低支撑物的高度。"
      ]
    }
  },
  "knee": {
    "de": {
      "name": "Knie-Liegestütze",
      "summary": "Vereinfachte Variante mit Knien als Auflagepunkt — ideal für Einsteiger.",
      "instructions": [
        "Knie auf dem Boden, Füße angehoben oder gekreuzt.",
        "Hände schulterbreit, gerade Linie von Knien bis Schultern.",
        "Hüfte stabil halten — nicht durchhängen oder hochschieben.",
        "Brust kontrolliert absenken, dann wieder hochdrücken."
      ],
      "tips": [
        "Nutze Knie-Liegestütze, bis du 3×8 saubere Wiederholungen schaffst, dann steige auf Standard um."
      ]
    },
    "el": {
      "name": "Πιέσεις από τα γόνατα",
      "summary": "Πιο εύκολη παραλλαγή με τα γόνατα στο πάτωμα — ιδανική για αρχάριους.",
      "instructions": [
        "Γόνατα στο πάτωμα, πέλματα ανασηκωμένα ή σταυρωμένα.",
        "Χέρια στο πλάτος των ώμων, κράτα ίσια γραμμή από τα γόνατα ως τους ώμους.",
        "Σταθερή λεκάνη — μην την αφήνεις να πέσει ούτε να ανέβει.",
        "Κατέβασε ελεγχόμενα το στήθος και μετά σπρώξε προς τα πάνω."
      ],
      "tips": [
        "Μείνε στις πιέσεις από τα γόνατα μέχρι να καταφέρεις 3×8 καθαρές επαναλήψεις, και μετά πέρασε στην κανονική εκδοχή."
      ]
    },
    "en": {
      "name": "Knee push-up",
      "summary": "Easier regression with the knees on the floor — ideal for beginners.",
      "instructions": [
        "Place the knees on the floor, feet lifted or crossed.",
        "Hands shoulder-width, keep a straight line from knees to shoulders.",
        "Stabilise the hips — no sagging or piking.",
        "Lower the chest under control, then press back up."
      ],
      "tips": [
        "Stay on knee push-ups until you can do 3×8 clean reps, then progress to the standard version."
      ]
    },
    "es": {
      "name": "Flexión de rodillas",
      "summary": "Regresión más fácil con las rodillas en el suelo — ideal para principiantes.",
      "instructions": [
        "Coloca las rodillas en el suelo, pies levantados o cruzados.",
        "Manos a la anchura de los hombros, mantén una línea recta de rodillas a hombros.",
        "Estabiliza las caderas — sin hundirlas ni elevarlas.",
        "Baja el pecho de forma controlada y luego empuja hacia arriba."
      ],
      "tips": [
        "Quédate con las flexiones de rodillas hasta poder hacer 3×8 repeticiones limpias, luego progresa a la versión estándar."
      ]
    },
    "fr": {
      "name": "Pompe sur les genoux",
      "summary": "Régression facilitée avec les genoux au sol — idéale pour les débutants.",
      "instructions": [
        "Placez les genoux au sol, pieds levés ou croisés.",
        "Mains à largeur d'épaules, gardez une ligne droite des genoux aux épaules.",
        "Stabilisez les hanches — pas d'affaissement ni de levée des fesses.",
        "Descendez la poitrine de façon contrôlée, puis repoussez vers le haut."
      ],
      "tips": [
        "Restez sur les pompes sur les genoux jusqu'à pouvoir faire 3×8 répétitions propres, puis passez à la version standard."
      ]
    },
    "it": {
      "name": "Piegamento sulle ginocchia",
      "summary": "Regressione facilitata con le ginocchia a terra — ideale per i principianti.",
      "instructions": [
        "Posiziona le ginocchia a terra, piedi sollevati o incrociati.",
        "Mani alla larghezza delle spalle, mantieni una linea retta dalle ginocchia alle spalle.",
        "Stabilizza i fianchi — senza cedimenti o sollevamenti.",
        "Abbassa il petto in modo controllato, poi risali."
      ],
      "tips": [
        "Rimani sui piegamenti sulle ginocchia finché riesci a fare 3×8 ripetizioni pulite, poi passa alla versione standard."
      ]
    },
    "nl": {
      "name": "Knieopdruk",
      "summary": "Makkelijkere regressie met knieën op de vloer — ideaal voor beginners.",
      "instructions": [
        "Plaats de knieën op de vloer, voeten omhoog of gekruist.",
        "Handen schouderbreedte, houd een rechte lijn van knieën tot schouders.",
        "Stabiliseer de heupen — niet doorzakken of ophogen.",
        "Laat de borst gecontroleerd zakken, druk dan terug omhoog."
      ],
      "tips": [
        "Blijf op knieopdrukken totdat je 3×8 schone herhalingen kunt doen, ga dan door naar de standaardversie."
      ]
    },
    "no": {
      "name": "Armhevning på knærne",
      "summary": "Enklere variant med knærne på gulvet – ideell for nybegynnere.",
      "instructions": [
        "Plasser knærne på gulvet, føttene løftet eller krysset.",
        "Hendene skulderbredde fra hverandre, hold en rett linje fra knær til skuldre.",
        "Stabiliser hoften – ingen nedsinking eller piking.",
        "Senk brystet med kontroll, og press deretter oppover igjen."
      ],
      "tips": [
        "Hold deg til armhevninger på knærne til du kan gjøre 3×8 rene repetisjoner, og gå deretter videre til standardversjonen."
      ]
    },
    "zh": {
      "name": "跪姿俯卧撑",
      "summary": "膝盖着地的简化版本——特别适合初学者。",
      "instructions": [
        "膝盖放在地面上，脚抬起或交叉。",
        "双手与肩同宽，从膝盖到肩膀保持一直线。",
        "稳定髋部——不要下沉或向上翘起。",
        "控制速度下降胸部，然后向上按压。"
      ],
      "tips": [
        "坚持做跪姿俯卧撑，直到能做3组8次干净的动作，然后升级到标准版本。"
      ]
    }
  },
  "knuckle": {
    "de": {
      "name": "Faust-Liegestütze",
      "summary": "Auf den Knöcheln statt mit flachen Händen — schont die Handgelenke und stärkt Unterarme.",
      "instructions": [
        "Hände zu Fäusten ballen, auf den ersten zwei Knöcheln (Zeige- und Mittelfinger) abstützen.",
        "Handrücken gerade — Handgelenk nicht knicken.",
        "Auf weichem Untergrund (Matte, Handtuch) starten, später auf hartem Boden.",
        "Sonst wie Standard-Liegestütze ausführen."
      ],
      "tips": [
        "Hilfreich bei empfindlichen Handgelenken — Belastung wandert vom Gelenk in die Fingerknöchel."
      ]
    },
    "el": {
      "name": "Πιέσεις στις γροθιές",
      "summary": "Στις αρθρώσεις των δαχτύλων αντί για ανοιχτές παλάμες — προστατεύει τους καρπούς και δυναμώνει τα αντιβράχια.",
      "instructions": [
        "Σφίξε τα χέρια σε γροθιές και στηρίξου στις δύο πρώτες αρθρώσεις (δείκτη και μέσου).",
        "Κράτα την ράχη της παλάμης ίσια — μη λυγίζεις τον καρπό.",
        "Ξεκίνα σε μαλακή επιφάνεια (στρώμα, πετσέτα) και αργότερα πέρνα σε σκληρό πάτωμα.",
        "Κατά τα άλλα η εκτέλεση είναι ίδια με τις κανονικές πιέσεις."
      ],
      "tips": [
        "Χρήσιμες για ευαίσθητους καρπούς — το φορτίο μετατοπίζεται από την άρθρωση στις αρθρώσεις των δαχτύλων."
      ]
    },
    "en": {
      "name": "Knuckle push-up",
      "summary": "Done on the knuckles instead of flat hands — easier on the wrists and strengthens the forearms.",
      "instructions": [
        "Make fists, support on the first two knuckles (index and middle finger).",
        "Keep the back of the hand straight — do not bend the wrist.",
        "Start on a soft surface (mat, towel), progress to hard floor later.",
        "Otherwise execute like a standard push-up."
      ],
      "tips": [
        "Useful for sensitive wrists — load shifts from the joint into the knuckles."
      ]
    },
    "es": {
      "name": "Flexión en nudillos",
      "summary": "Se realiza sobre los nudillos en lugar de las palmas planas — alivia las muñecas y fortalece los antebrazos.",
      "instructions": [
        "Cierra los puños, apóyate sobre los dos primeros nudillos (índice y corazón).",
        "Mantén el dorso de la mano recto — no dobles la muñeca.",
        "Empieza sobre una superficie blanda (esterilla, toalla) y progresa después al suelo duro.",
        "Por lo demás, ejecútala como una flexión estándar."
      ],
      "tips": [
        "Útil para muñecas sensibles — la carga se desplaza de la articulación a los nudillos."
      ]
    },
    "fr": {
      "name": "Pompe sur les poings",
      "summary": "Réalisée sur les poings plutôt que les paumes — plus douce pour les poignets et renforce les avant-bras.",
      "instructions": [
        "Fermez les poings, appuyez-vous sur les deux premières jointures (index et majeur).",
        "Gardez le dos de la main droit — ne fléchissez pas le poignet.",
        "Commencez sur une surface souple (tapis, serviette), puis progressez vers un sol dur.",
        "Exécutez sinon comme une pompe standard."
      ],
      "tips": [
        "Utile pour les poignets sensibles — la charge se déplace de l'articulation vers les jointures."
      ]
    },
    "it": {
      "name": "Piegamento sulle nocche",
      "summary": "Eseguito sulle nocche invece che con le mani piatte — più delicato per i polsi e rafforza gli avambracci.",
      "instructions": [
        "Fai i pugni, appoggiati sulle prime due nocche (indice e medio).",
        "Mantieni il dorso della mano dritto — non piegare il polso.",
        "Inizia su una superficie morbida (tappetino, asciugamano), poi progredisci verso il pavimento duro.",
        "Per il resto, esegui come un piegamento standard."
      ],
      "tips": [
        "Utile per polsi sensibili — il carico si sposta dall'articolazione alle nocche."
      ]
    },
    "nl": {
      "name": "Vuistopdruk",
      "summary": "Uitgevoerd op de knokkels in plaats van platte handen — vriendelijker voor de polsen en versterkt de onderarmen.",
      "instructions": [
        "Maak vuisten, steun op de eerste twee knokkels (wijsvinger en middelvinger).",
        "Houd de rugzijde van de hand recht — buig de pols niet.",
        "Begin op een zacht oppervlak (mat, handdoek), ga later over naar een harde vloer.",
        "Voer verder uit als een standaard opdruk."
      ],
      "tips": [
        "Nuttig bij gevoelige polsen — de belasting verschuift van het gewricht naar de knokkels."
      ]
    },
    "no": {
      "name": "Armhevning på knokene",
      "summary": "Gjøres på knokene i stedet for flate hender – lettere på håndleddene og styrker underarmene.",
      "instructions": [
        "Lag knyttneve, støtt på de to første knokene (peke- og langefingerens knoker).",
        "Hold baksiden av hånden rett – ikke bøy håndleddet.",
        "Start på en myk overflate (matte, håndkle), gå videre til hardt gulv senere.",
        "Utfør ellers som en standard armhevning."
      ],
      "tips": [
        "Nyttig for sensitive håndledd – belastningen flyttes fra leddet til knokene."
      ]
    },
    "zh": {
      "name": "拳式俯卧撑",
      "summary": "用拳头关节而不是平手做俯卧撑——对腕部压力小，强化前臂。",
      "instructions": [
        "握拳，支撑在前两个关节（食指和中指）。",
        "保持手背笔直——不要弯曲腕部。",
        "先在柔软的表面开始（瑜伽垫、毛巾），之后再在硬地面上进行。",
        "其他动作与标准俯卧撑相同。"
      ],
      "tips": [
        "对腕部敏感的人很有用——负荷从关节转移到了拳头。"
      ]
    }
  },
  "negative-one-arm": {
    "de": {
      "name": "Negative Einarmige",
      "summary": "Nur die Absenkphase einarmig — kontrollierte Exzentrik baut die Kraft für die volle Bewegung auf.",
      "instructions": [
        "Eine Hand auf einer Bank/Erhöhung, Füße breit für Stabilität.",
        "Andere Hand am Rücken oder seitlich, Körper als Plank halten.",
        "In 3-5 Sekunden langsam zur Bank absenken — keine \"Aufschlag\"-Phase.",
        "Mit beiden Händen oder von der erhöhten Position hochdrücken — die positive Phase wird hier nicht einarmig gemacht."
      ],
      "tips": [
        "Bauen Sie die negative Zeit langsam aus: 3 s → 5 s → 8 s über mehrere Wochen."
      ]
    },
    "el": {
      "name": "Αρνητικές πιέσεις με έναν βραχίονα",
      "summary": "Μόνο η φάση καταβίβασης γίνεται με έναν βραχίονα — η ελεγχόμενη έκκεντρη φάση χτίζει τη δύναμη για την πλήρη κίνηση.",
      "instructions": [
        "Τοποθέτησε το ένα χέρι σε πάγκο ή ύψωμα· πόδια ανοιχτά για σταθερότητα.",
        "Το άλλο χέρι στη μέση ή στο πλάι, κράτα το σώμα σαν σανίδα.",
        "Κατέβα προς τον πάγκο σε 3–5 δευτερόλεπτα — χωρίς «πτώση».",
        "Σπρώξε προς τα πάνω με τα δύο χέρια ή από την ψηλή θέση — η ανοδική φάση εδώ δεν γίνεται με έναν βραχίονα."
      ],
      "tips": [
        "Αύξανε τον έκκεντρο χρόνο σταδιακά: 3΄΄ → 5΄΄ → 8΄΄ μέσα σε αρκετές εβδομάδες."
      ]
    },
    "en": {
      "name": "Negative one-arm push-up",
      "summary": "Only the lowering phase done one-armed — a controlled eccentric builds the strength for the full movement.",
      "instructions": [
        "Place one hand on a bench/elevation; feet wide for stability.",
        "Other hand on the lower back or hip; hold the body as a plank.",
        "Lower toward the bench over 3-5 seconds — no \"crash\" phase.",
        "Press up with both hands or from the elevated position — the concentric is not done one-armed here."
      ],
      "tips": [
        "Build the eccentric time slowly: 3 s → 5 s → 8 s across multiple weeks."
      ]
    },
    "es": {
      "name": "Flexión negativa de un solo brazo",
      "summary": "Solo la fase de descenso se realiza con un solo brazo — una excéntrica controlada desarrolla la fuerza para el movimiento completo.",
      "instructions": [
        "Coloca una mano sobre un banco o elevación; pies bien separados para mayor estabilidad.",
        "La otra mano en la zona lumbar o la cadera; mantén el cuerpo como una plancha.",
        "Desciende hacia el banco durante 3–5 segundos — sin fase de \"caída\".",
        "Empuja hacia arriba con ambas manos o desde la posición elevada — la fase concéntrica no se realiza con un solo brazo aquí."
      ],
      "tips": [
        "Aumenta el tiempo excéntrico gradualmente: 3 s → 5 s → 8 s a lo largo de varias semanas."
      ]
    },
    "fr": {
      "name": "Pompe négative à un bras",
      "summary": "Seulement la phase de descente effectuée à un bras — un excentrique contrôlé développe la force pour le mouvement complet.",
      "instructions": [
        "Placez une main sur un banc ou une élévation ; pieds bien écartés pour la stabilité.",
        "L'autre main sur le bas du dos ou la hanche ; maintenez le corps en planche.",
        "Descendez vers le banc sur 3 à 5 secondes — sans phase de « chute ».",
        "Repoussez avec les deux mains ou depuis la position surélevée — la phase concentrique ne se fait pas à un bras ici."
      ],
      "tips": [
        "Augmentez progressivement le temps excentrique : 3 s → 5 s → 8 s sur plusieurs semaines."
      ]
    },
    "it": {
      "name": "Piegamento negativo a un braccio",
      "summary": "Solo la fase di discesa eseguita con un braccio — un eccentrico controllato costruisce la forza per il movimento completo.",
      "instructions": [
        "Posiziona una mano su una panca/rialzo; piedi larghi per la stabilità.",
        "L'altra mano sulla zona lombare o sul fianco; mantieni il corpo come una plank.",
        "Abbassa verso la panca in 3-5 secondi — senza \"caduta\" improvvisa.",
        "Risali con entrambe le mani o dalla posizione elevata — la fase concentrica non è a un braccio."
      ],
      "tips": [
        "Aumenta gradualmente il tempo eccentrico: 3 s → 5 s → 8 s nell'arco di più settimane."
      ]
    },
    "nl": {
      "name": "Negatieve eénarmige opdruk",
      "summary": "Alleen de neerwaartse fase éénarmig uitgevoerd — een gecontroleerde excentrische beweging bouwt de kracht op voor de volledige beweging.",
      "instructions": [
        "Plaats één hand op een bank/verhoging; voeten breed voor stabiliteit.",
        "Andere hand op de lage rug of heup; houd het lichaam als een plank.",
        "Zak in 3–5 seconden naar de bank — geen \"val\"-fase.",
        "Druk omhoog met beide handen of vanuit de verhoogde positie — de concentrische fase is hier niet éénarmig."
      ],
      "tips": [
        "Bouw de excentrische tijd langzaam op: 3 s → 5 s → 8 s over meerdere weken."
      ]
    },
    "no": {
      "name": "Negativ enarms armhevning",
      "summary": "Kun nedstigningsfasen gjøres med én arm – en kontrollert eksentrisk bevegelse bygger styrken som trengs til fullbevegelsen.",
      "instructions": [
        "Plasser en arm på en benk/forhøyning; føttene bredt for stabilitet.",
        "Den andre armen på nedre del av ryggen eller hoften; hold kroppen som en planke.",
        "Senk nedover mot benken over 3-5 sekunder – ingen \"krasj\"-fase.",
        "Press oppover med begge armene eller fra forhøyningen – den konsentriske fasen gjøres ikke enarmede her."
      ],
      "tips": [
        "Bygg den eksentriske tiden gradvis: 3 s → 5 s → 8 s over flere uker."
      ]
    },
    "zh": {
      "name": "离心单臂俯卧撑",
      "summary": "仅在下降阶段用单臂——控制的离心收缩能为完整动作建立力量基础。",
      "instructions": [
        "一只手放在长凳或抬高物体上，脚分开以获得稳定性。",
        "另一只手放在下背部或髋部，保持身体成平板。",
        "花3-5秒时间控制下降到长凳——不要\"坠落\"。",
        "用双手按压或从抬高位置向上按压——向心收缩不是单臂完成。"
      ],
      "tips": [
        "逐步增加离心时间：3秒→5秒→8秒，跨越多周进行。"
      ]
    }
  },
  "one-arm": {
    "de": {
      "name": "Einarmige Liegestütze",
      "summary": "Volle Liegestütze mit einer Hand — Königsklasse der Brust-/Trizepsübungen.",
      "instructions": [
        "Füße deutlich breiter als hüftbreit für maximale Stabilität (anfangs sehr breit).",
        "Eine Hand unter der Brustmitte, andere am Rücken oder seitlich.",
        "Körper bewusst als Plank halten — Hüfte und Schultern dürfen nicht rotieren.",
        "Brust kontrolliert zur Hand absenken, dann gerade hochdrücken.",
        "Mit fortschreitender Kraft die Standbreite Schritt für Schritt verringern."
      ],
      "tips": [
        "Wiederholungen werden pro Seite gezählt — dominante Seite zuerst, schwächere danach."
      ]
    },
    "el": {
      "name": "Πιέσεις με έναν βραχίονα",
      "summary": "Πλήρης πίεση με το ένα χέρι — η βασίλισσα των ασκήσεων με το βάρος του σώματος για στήθος και τρικέφαλους.",
      "instructions": [
        "Πόδια αισθητά πιο φαρδιά από το πλάτος της λεκάνης για μέγιστη σταθερότητα (στην αρχή πολύ ανοιχτά).",
        "Το ένα χέρι κάτω από το κέντρο του στήθους· το άλλο στη μέση ή στο πλάι.",
        "Κράτα συνειδητά το σώμα σαν σανίδα — η λεκάνη και οι ώμοι δεν πρέπει να περιστρέφονται.",
        "Κατέβασε ελεγχόμενα το στήθος ως το χέρι και σπρώξε ίσια προς τα πάνω.",
        "Καθώς αυξάνεται η δύναμη, μείωσε σταδιακά το άνοιγμα των ποδιών."
      ],
      "tips": [
        "Οι επαναλήψεις μετριούνται ανά πλευρά — ξεκίνα από το δυνατό χέρι και αντιστοίχισε τον αριθμό στο αδύναμο."
      ]
    },
    "en": {
      "name": "One-arm push-up",
      "summary": "Full push-up with a single hand — the king of bodyweight pressing.",
      "instructions": [
        "Feet noticeably wider than hip-width for maximum stability (very wide at the start).",
        "One hand under the centre of the chest; the other on the lower back or hip.",
        "Hold the body intentionally as a plank — hips and shoulders must not rotate.",
        "Lower the chest to the hand under control, then press straight up.",
        "As strength grows, narrow the foot stance step by step."
      ],
      "tips": [
        "Reps are counted per side — start with the dominant side and match it on the weaker side."
      ]
    },
    "es": {
      "name": "Flexión de un solo brazo",
      "summary": "Flexión completa con una sola mano — el rey del press con peso corporal.",
      "instructions": [
        "Pies notablemente más separados que la anchura de las caderas para la máxima estabilidad (muy abiertos al principio).",
        "Una mano bajo el centro del pecho; la otra en la zona lumbar o la cadera.",
        "Mantén el cuerpo intencionadamente como una plancha — las caderas y los hombros no deben rotar.",
        "Baja el pecho hacia la mano de forma controlada y luego empuja recto hacia arriba.",
        "A medida que aumenta la fuerza, reduce progresivamente la separación de los pies."
      ],
      "tips": [
        "Las repeticiones se cuentan por lado — empieza con el lado dominante e iguálalo en el lado más débil."
      ]
    },
    "fr": {
      "name": "Pompe à un bras",
      "summary": "Pompe complète avec une seule main — la reine des exercices de poussée au poids du corps.",
      "instructions": [
        "Pieds nettement plus larges que la largeur des hanches pour une stabilité maximale (très large au départ).",
        "Une main sous le centre de la poitrine ; l'autre sur le bas du dos ou la hanche.",
        "Maintenez intentionnellement le corps en planche — les hanches et les épaules ne doivent pas pivoter.",
        "Descendez la poitrine jusqu'à la main de façon contrôlée, puis poussez droit vers le haut.",
        "À mesure que la force augmente, réduisez progressivement l'écartement des pieds."
      ],
      "tips": [
        "Les répétitions se comptent par côté — commencez par le côté dominant et égalisez sur le côté faible."
      ]
    },
    "it": {
      "name": "Piegamento a un braccio",
      "summary": "Piegamento completo con una sola mano — il re della spinta a corpo libero.",
      "instructions": [
        "Piedi notevolmente più larghi della larghezza dei fianchi per la massima stabilità (molto larghi all'inizio).",
        "Una mano sotto il centro del petto; l'altra sulla zona lombare o sul fianco.",
        "Mantieni il corpo intenzionalmente come una plank — fianchi e spalle non devono ruotare.",
        "Abbassa il petto fino alla mano in modo controllato, poi spingi direttamente verso l'alto.",
        "Man mano che la forza cresce, riduci gradualmente la larghezza dei piedi."
      ],
      "tips": [
        "Le ripetizioni si contano per lato — inizia con il lato dominante e pareggiale sul lato più debole."
      ]
    },
    "nl": {
      "name": "Eénarmige opdruk",
      "summary": "Volledige opdruk met één hand — de koning van lichaamsgewicht-drukken.",
      "instructions": [
        "Voeten duidelijk breder dan heupbreedte voor maximale stabiliteit (zeer breed aan het begin).",
        "Één hand onder het midden van de borst; de andere op de lage rug of heup.",
        "Houd het lichaam bewust als een plank — heupen en schouders mogen niet roteren.",
        "Laat de borst gecontroleerd zakken naar de hand, druk dan recht omhoog.",
        "Verklein de voetbreedte geleidelijk naarmate de kracht toeneemt."
      ],
      "tips": [
        "Herhalingen worden per kant geteld — begin met de dominante kant en evenaar dat op de zwakkere kant."
      ]
    },
    "no": {
      "name": "Enarms armhevning",
      "summary": "Full armhevning med én hånd – kongen blant kroppsvektøvelser.",
      "instructions": [
        "Plasser føttene merkbart bredere enn hofteavstanden for maksimal stabilitet (veldig bredt til å begynne med).",
        "En arm under midten av brystet; den andre på nedre del av ryggen eller hoften.",
        "Hold kroppen bevisst som en planke – hoften og skulderne må ikke rotere.",
        "Senk brystet ned til hånden med kontroll, og press deretter rett oppover.",
        "Ettersom styrken øker, smalner du fotposisjonen gradvis."
      ],
      "tips": [
        "Repetisjoner telles per side – start med den dominante siden og matcher den på den svakere siden."
      ]
    },
    "zh": {
      "name": "单臂俯卧撑",
      "summary": "用单手完成的完整俯卧撑——徒手按压的巅峰之作。",
      "instructions": [
        "脚明显分开超过臀宽以获得最大稳定性（开始时脚距更宽）。",
        "一只手放在胸部中心下方，另一只手放在下背部或髋部。",
        "刻意保持身体成平板——髋部和肩膀不能旋转。",
        "控制速度将胸部下降至手部，然后直接向上按压。",
        "力量增长时，逐步缩小脚距。"
      ],
      "tips": [
        "每一侧单独计次——从强侧开始，然后在弱侧达成相同次数。"
      ]
    }
  },
  "partial-one-arm": {
    "de": {
      "name": "Partielle Einarmige",
      "summary": "Einarmige Liegestütze über reduzierten Bewegungsumfang (z. B. von einer niedrigen Bank).",
      "instructions": [
        "Eine Hand auf einer niedrigen Bank/Stufe, Füße sehr breit (mindestens hüftbreit).",
        "Andere Hand am Rücken, Körper als Plank — Hüfte nicht rotieren lassen.",
        "Bewusst nur bis zur Bankhöhe absenken (reduzierter ROM).",
        "Mit der einen Hand hochdrücken; Höhe der Bank schrittweise reduzieren."
      ],
      "tips": []
    },
    "el": {
      "name": "Πιέσεις με έναν βραχίονα μερικού εύρους",
      "summary": "Πιέσεις με έναν βραχίονα σε μειωμένο εύρος κίνησης (π.χ. από χαμηλό πάγκο).",
      "instructions": [
        "Τοποθέτησε το ένα χέρι σε χαμηλό πάγκο ή σκαλοπάτι· πόδια πολύ ανοιχτά (τουλάχιστον στο πλάτος της λεκάνης).",
        "Το άλλο χέρι στη μέση, κράτα το σώμα σαν σανίδα — μην αφήνεις τη λεκάνη να περιστρέφεται.",
        "Κατέβα συνειδητά μόνο μέχρι το ύψος του πάγκου (μειωμένο εύρος κίνησης).",
        "Σπρώξε προς τα πάνω με το ένα χέρι· μείωσε σταδιακά το ύψος του πάγκου."
      ],
      "tips": []
    },
    "en": {
      "name": "Partial-ROM one-arm push-up",
      "summary": "One-arm push-ups over a reduced range of motion (e.g. from a low bench).",
      "instructions": [
        "Place one hand on a low bench/step; feet very wide (at least hip-width).",
        "Other hand on the lower back; hold the body as a plank — do not rotate the hips.",
        "Intentionally only descend to the bench height (reduced ROM).",
        "Press up one-armed; lower the bench height progressively."
      ],
      "tips": []
    },
    "es": {
      "name": "Flexión de un solo brazo con rango parcial",
      "summary": "Flexiones de un solo brazo con rango de movimiento reducido (p. ej. desde un banco bajo).",
      "instructions": [
        "Coloca una mano sobre un banco o escalón bajo; pies muy separados (al menos a la anchura de las caderas).",
        "La otra mano en la zona lumbar; mantén el cuerpo como una plancha — no rotes las caderas.",
        "Desciende intencionadamente solo hasta la altura del banco (ROM reducido).",
        "Empuja hacia arriba con un solo brazo; reduce progresivamente la altura del banco."
      ],
      "tips": []
    },
    "fr": {
      "name": "Pompe à un bras en amplitude partielle",
      "summary": "Pompes à un bras sur une amplitude de mouvement réduite (ex. depuis un banc bas).",
      "instructions": [
        "Placez une main sur un banc bas ou une marche ; pieds très écartés (au moins largeur des hanches).",
        "L'autre main sur le bas du dos ; maintenez le corps en planche — ne faites pas pivoter les hanches.",
        "Descendez intentionnellement seulement jusqu'à la hauteur du banc (amplitude réduite).",
        "Poussez vers le haut à un bras ; abaissez progressivement la hauteur du banc."
      ],
      "tips": []
    },
    "it": {
      "name": "Piegamento parziale a un braccio",
      "summary": "Piegamenti a un braccio su range di movimento ridotto (es. da una panca bassa).",
      "instructions": [
        "Posiziona una mano su una panca/scalino basso; piedi molto larghi (almeno larghezza fianchi).",
        "L'altra mano sulla zona lombare; mantieni il corpo come una plank — non ruotare i fianchi.",
        "Scendi intenzionalmente solo fino all'altezza della panca (ROM ridotto).",
        "Spingi su con un braccio; abbassa progressivamente l'altezza della panca."
      ],
      "tips": []
    },
    "nl": {
      "name": "Eénarmige opdruk met beperkt bewegingsbereik",
      "summary": "Eénarmige opdrukken over een beperkt bewegingsbereik (bijv. vanaf een lage bank).",
      "instructions": [
        "Plaats één hand op een lage bank/opstap; voeten zeer breed (minimaal heupbreedte).",
        "Andere hand op de lage rug; houd het lichaam als een plank — roteer de heupen niet.",
        "Zak bewust alleen tot de bankhoogte (beperkt bewegingsbereik).",
        "Druk éénarmig omhoog; verlaag de bankhoogte progressief."
      ],
      "tips": []
    },
    "no": {
      "name": "Enarms armhevning med redusert ROM",
      "summary": "Enarms armhevninger over redusert bevegelsesutslag (f.eks. fra en lav benk).",
      "instructions": [
        "Plasser én arm på en lav benk/trinn; føttene veldig bredt (minst hofteavstand).",
        "Den andre armen på nedre del av ryggen; hold kroppen som en planke – ikke roter hoften.",
        "Senk kontrollert kun ned til benkhøyden (redusert ROM).",
        "Press oppover med én arm; senk benkhøyden gradvis."
      ],
      "tips": []
    },
    "zh": {
      "name": "部分范围单臂俯卧撑",
      "summary": "在减小活动范围的情况下进行单臂俯卧撑（例如从低长凳）。",
      "instructions": [
        "一只手放在低长凳或台阶上，脚分开很宽（至少臀宽）。",
        "另一只手放在下背部，保持身体成平板——不要旋转髋部。",
        "故意只下降到长凳的高度（减小活动范围）。",
        "单臂向上按压，逐步降低长凳高度。"
      ],
      "tips": []
    }
  },
  "pike": {
    "de": {
      "name": "Pike-Liegestütze",
      "summary": "Liegestütze in V-Position — fast vertikales Drücken, Vorstufe zu Handstand-Liegestützen.",
      "instructions": [
        "Aus dem Vierfüßlerstand Hüfte nach oben schieben — Körper bildet ein umgekehrtes V.",
        "Hände schulterbreit, Beine gestreckt oder leicht gebeugt, Po hoch.",
        "Kopf zwischen den Armen Richtung Boden senken — Ellenbogen nach hinten.",
        "Wieder hochdrücken, ohne in eine Liegestützposition abzukippen."
      ],
      "tips": [
        "Schwieriger machen: Füße auf eine Erhöhung stellen, fast vertikale Position."
      ]
    },
    "el": {
      "name": "Πιέσεις pike",
      "summary": "Πιέσεις σε σχήμα ανεστραμμένου V — σχεδόν κατακόρυφο σπρώξιμο, ενδιάμεσο βήμα προς τις πιέσεις σε στάση χεριών.",
      "instructions": [
        "Από τη θέση τετράποδης στήριξης, ανέβασε τη λεκάνη — το σώμα σχηματίζει ανεστραμμένο V.",
        "Χέρια στο πλάτος των ώμων, πόδια ίσια ή ελαφρώς λυγισμένα, λεκάνη ψηλά.",
        "Κατέβασε το κεφάλι ανάμεσα στους βραχίονες προς το πάτωμα — οι αγκώνες κοιτούν προς τα πίσω.",
        "Σπρώξε ξανά προς τα πάνω χωρίς να πέσεις στην κανονική θέση πιέσεων."
      ],
      "tips": [
        "Πιο δύσκολη παραλλαγή: τοποθέτησε τα πόδια σε ύψωμα για σχεδόν κατακόρυφη θέση."
      ]
    },
    "en": {
      "name": "Pike push-up",
      "summary": "Push-ups from a V-shape — near-vertical pressing, a stepping stone to handstand push-ups.",
      "instructions": [
        "From a quadruped position push the hips up — the body forms an inverted V.",
        "Hands shoulder-width, legs straight or slightly bent, hips high.",
        "Lower the head between the arms toward the floor — elbows track back.",
        "Press back up without dropping into a regular push-up position."
      ],
      "tips": [
        "Make it harder: put the feet on an elevation for a near-vertical position."
      ]
    },
    "es": {
      "name": "Flexión de pica",
      "summary": "Flexiones desde una forma en V — press casi vertical, un escalón previo a las flexiones en pino.",
      "instructions": [
        "Desde una posición a cuatro patas, eleva las caderas — el cuerpo forma una V invertida.",
        "Manos a la anchura de los hombros, piernas rectas o ligeramente dobladas, caderas altas.",
        "Baja la cabeza entre los brazos hacia el suelo — los codos van hacia atrás.",
        "Empuja de nuevo hacia arriba sin caer a la posición de flexión normal."
      ],
      "tips": [
        "Para hacerlo más difícil: pon los pies sobre una elevación para una posición casi vertical."
      ]
    },
    "fr": {
      "name": "Pompe pike",
      "summary": "Pompes depuis une position en V inversé — poussée quasi verticale, un tremplin vers les pompes sur les mains.",
      "instructions": [
        "Depuis une position à quatre pattes, poussez les hanches vers le haut — le corps forme un V inversé.",
        "Mains à largeur d'épaules, jambes tendues ou légèrement fléchies, hanches hautes.",
        "Descendez la tête entre les bras vers le sol — les coudes s'orientent vers l'arrière.",
        "Repoussez vers le haut sans retomber en position de pompe classique."
      ],
      "tips": [
        "Pour rendre plus difficile : placez les pieds sur une élévation pour une position quasi verticale."
      ]
    },
    "it": {
      "name": "Piegamento a picco",
      "summary": "Piegamenti dalla posizione a V rovesciata — spinta quasi verticale, un passaggio verso i piegamenti in verticale.",
      "instructions": [
        "Da una posizione quadrupede, spingi i fianchi verso l'alto — il corpo forma una V rovesciata.",
        "Mani alla larghezza delle spalle, gambe tese o leggermente piegate, fianchi alti.",
        "Abbassa la testa tra le braccia verso il pavimento — i gomiti puntano all'indietro.",
        "Risali senza cedere nella posizione di piegamento normale."
      ],
      "tips": [
        "Per renderlo più difficile: metti i piedi su un rialzo per una posizione quasi verticale."
      ]
    },
    "nl": {
      "name": "Pike-opdruk",
      "summary": "Opdrukken vanuit een V-vorm — bijna verticaal drukken, een opstap naar handstand-opdrukken.",
      "instructions": [
        "Duw vanuit een viervoeter de heupen omhoog — het lichaam vormt een omgekeerde V.",
        "Handen schouderbreedte, benen recht of licht gebogen, heupen hoog.",
        "Laat het hoofd tussen de armen zakken richting de vloer — ellebogen bewegen naar achteren.",
        "Druk terug omhoog zonder terug in een gewone opdrukpositie te zakken."
      ],
      "tips": [
        "Maak het moeilijker: zet de voeten op een verhoging voor een bijna verticale positie."
      ]
    },
    "no": {
      "name": "Pike armhevning",
      "summary": "Armhevninger fra en V-form – nær-vertikal press, et springbrett til håndstand armhevninger.",
      "instructions": [
        "Fra en firbent posisjon presser du hoften oppover – kroppen danner en invertert V.",
        "Hendene skulderbredde fra hverandre, ben rette eller litt bøyd, hoften høyt.",
        "Senk hodet mellom armene mot gulvet – albueleddet følger bakover.",
        "Press oppover uten å falle ned i en regulær armhevningsposisjon."
      ],
      "tips": [
        "Gjør det vanskeligere: plasser føttene på en forhøyning for en nær-vertikal posisjon."
      ]
    },
    "zh": {
      "name": "派克俯卧撑",
      "summary": "从V形姿态做俯卧撑——接近竖直的按压，通往倒立撑的垫脚石。",
      "instructions": [
        "从四足跪地姿态向上推髋部——身体形成倒V形。",
        "双手与肩同宽，腿笔直或微微弯曲，髋部抬高。",
        "将头部下降至双臂之间朝向地面——肘部向后追踪。",
        "向上按压而不是掉入常规俯卧撑位置。"
      ],
      "tips": [
        "增加难度：将脚放在抬高物体上，实现接近竖直的位置。"
      ]
    }
  },
  "standard": {
    "de": {
      "name": "Standard-Liegestütze",
      "summary": "Klassische Liegestütze mit schulterbreitem Stand und gerader Körperlinie.",
      "instructions": [
        "Hände schulterbreit, direkt unter den Schultern, Finger zeigen nach vorne.",
        "Körper bildet eine gerade Linie von Kopf bis Ferse — Bauch und Po angespannt.",
        "Ellenbogen in einem 45°-Winkel zum Oberkörper, nicht weit abspreizen.",
        "Brust kontrolliert in Richtung Boden senken, bis sie knapp darüber ist.",
        "Kraftvoll wieder hochdrücken, Ellenbogen oben nicht durchstrecken."
      ],
      "tips": [
        "Blick leicht nach vorne auf den Boden, nicht den Nacken überstrecken.",
        "Atmung: beim Absenken einatmen, beim Hochdrücken ausatmen."
      ]
    },
    "el": {
      "name": "Κλασικές πιέσεις",
      "summary": "Κλασικές πιέσεις με χέρια στο πλάτος των ώμων και ίσια γραμμή σώματος.",
      "instructions": [
        "Χέρια στο πλάτος των ώμων, ακριβώς κάτω από τους ώμους, δάχτυλα προς τα μπρος.",
        "Το σώμα σχηματίζει ίσια γραμμή από το κεφάλι ως τις φτέρνες — σφίξε κοιλιά και γλουτούς.",
        "Αγκώνες σε γωνία περίπου 45° με τον κορμό, μην τους ανοίγεις προς τα πλάγια.",
        "Κατέβασε ελεγχόμενα το στήθος μέχρι σχεδόν να αγγίξει το πάτωμα.",
        "Σπρώξε δυνατά προς τα πάνω, χωρίς να κλειδώνεις τους αγκώνες στην ψηλή θέση."
      ],
      "tips": [
        "Βλέμμα ελαφρώς προς τα μπρος στο πάτωμα — μην υπερεκτείνεις τον αυχένα.",
        "Αναπνοή: εισπνοή στην κατάβαση, εκπνοή στο σπρώξιμο προς τα πάνω."
      ]
    },
    "en": {
      "name": "Standard push-up",
      "summary": "Classic push-up with shoulder-width hand position and a straight body line.",
      "instructions": [
        "Hands shoulder-width apart, directly under the shoulders, fingers pointing forward.",
        "Body forms a straight line from head to heels — brace abs and glutes.",
        "Elbows at roughly 45° to the torso, not flared out wide.",
        "Lower the chest under control until it nearly touches the floor.",
        "Press back up powerfully, do not lock the elbows at the top."
      ],
      "tips": [
        "Look slightly forward at the floor — do not crane the neck.",
        "Breathing: inhale on the way down, exhale on the press up."
      ]
    },
    "es": {
      "name": "Flexión estándar",
      "summary": "Flexión clásica con las manos a la anchura de los hombros y una línea corporal recta.",
      "instructions": [
        "Manos a la anchura de los hombros, directamente bajo los hombros, dedos apuntando hacia adelante.",
        "El cuerpo forma una línea recta de la cabeza a los talones — activa abdominales y glúteos.",
        "Codos a aproximadamente 45° respecto al torso, sin abrirlos hacia los lados.",
        "Baja el pecho de forma controlada hasta que casi toque el suelo.",
        "Empuja hacia arriba con potencia, no bloquees los codos arriba."
      ],
      "tips": [
        "Mira ligeramente hacia delante en el suelo — no fuerces el cuello.",
        "Respiración: inhala en el descenso, exhala en el empuje hacia arriba."
      ]
    },
    "fr": {
      "name": "Pompe standard",
      "summary": "Pompe classique avec position des mains à largeur d'épaules et corps en ligne droite.",
      "instructions": [
        "Mains à largeur d'épaules, directement sous les épaules, doigts pointant vers l'avant.",
        "Corps en ligne droite de la tête aux talons — gainez abdominaux et fessiers.",
        "Coudes à environ 45° du torse, sans s'écarter sur les côtés.",
        "Descendez la poitrine de façon contrôlée jusqu'à ce qu'elle effleure presque le sol.",
        "Repoussez puissamment vers le haut, ne verrouillez pas les coudes en haut."
      ],
      "tips": [
        "Regardez légèrement devant vous vers le sol — ne tendez pas le cou.",
        "Respiration : inspirez à la descente, expirez à la poussée."
      ]
    },
    "it": {
      "name": "Piegamento standard",
      "summary": "Piegamento classico con mani alla larghezza delle spalle e corpo in linea retta.",
      "instructions": [
        "Mani alla larghezza delle spalle, direttamente sotto le spalle, dita rivolte in avanti.",
        "Il corpo forma una linea retta dalla testa ai talloni — tieni addominali e glutei in tensione.",
        "Gomiti a circa 45° rispetto al busto, non aperti verso l'esterno.",
        "Abbassa il petto in modo controllato finché sfiora quasi il pavimento.",
        "Risali con forza, senza bloccare i gomiti in cima."
      ],
      "tips": [
        "Guarda leggermente avanti verso il pavimento — non inarcare il collo.",
        "Respirazione: inspira nella discesa, espira nella spinta verso l'alto."
      ]
    },
    "nl": {
      "name": "Standaard opdruk",
      "summary": "Klassieke opdruk met schouderbreedte handpositie en een rechte lichaamslijn.",
      "instructions": [
        "Handen schouderbreedte, direct onder de schouders, vingers naar voren gericht.",
        "Lichaam vormt een rechte lijn van hoofd tot hielen — span buik en bilspieren aan.",
        "Ellebogen op ruwweg 45° ten opzichte van de romp, niet uitwaaierend.",
        "Laat de borst gecontroleerd zakken totdat die de vloer bijna raakt.",
        "Druk krachtig terug omhoog, vergrendel de ellebogen niet bovenaan."
      ],
      "tips": [
        "Kijk licht vooruit naar de vloer — rek de nek niet.",
        "Ademhaling: inademen bij het zakken, uitademen bij het omhoogdrukken."
      ]
    },
    "no": {
      "name": "Standard armhevning",
      "summary": "Klassisk armhevning med skulderbredde håndposisjon og en rett kroppslinje.",
      "instructions": [
        "Hendene skulderbredde fra hverandre, direkte under skulderne, fingrene peker fremover.",
        "Kroppen danner en rett linje fra hode til hæl – stram magen og setemusklene.",
        "Albueleddet ved omtrent 45° til kroppen, ikke spredt bredt ut til siden.",
        "Senk brystet med kontroll til det nesten berører gulvet.",
        "Press oppover kraftig, ikke lås albueleddet på toppen."
      ],
      "tips": [
        "Se litt fremover på gulvet – ikke strekk nakken.",
        "Pusting: pust inn på vei ned, pust ut på press oppover."
      ]
    },
    "zh": {
      "name": "标准俯卧撑",
      "summary": "经典俯卧撑，双手与肩同宽，身体成一直线。",
      "instructions": [
        "双手与肩膀同宽，位于肩膀正下方，手指向前。",
        "身体从头到脚跟成一直线——收紧腹部和臀部肌肉。",
        "肘部与躯干成约45°角，不要向外扩张。",
        "控制速度下降，胸部接近地面。",
        "有力地向上按压，在顶部不要锁定肘关节。"
      ],
      "tips": [
        "目光略微向前看地面——不要抬头看。",
        "呼吸节奏：下降时吸气，上升时呼气。"
      ]
    }
  },
  "wall-one-arm": {
    "de": {
      "name": "Wand-Einarmige",
      "summary": "Einarmige Liegestütze gegen die Wand — sichere Einstiegsübung für die einarmige Progression.",
      "instructions": [
        "In ungefähr einer Armlänge Abstand zur Wand stehen.",
        "Eine Hand auf Schulterhöhe an die Wand, andere Hand am Rücken oder seitlich.",
        "Körper als feste Linie kippen lassen, Ellenbogen kontrolliert beugen.",
        "Mit langsamer Exzentrik (3 s) Richtung Wand absenken, kraftvoll wegdrücken."
      ],
      "tips": []
    },
    "el": {
      "name": "Πιέσεις με έναν βραχίονα στον τοίχο",
      "summary": "Πιέσεις με έναν βραχίονα κόντρα σε τοίχο — ασφαλής εισαγωγική άσκηση για την προπόνηση του ενός βραχίονα.",
      "instructions": [
        "Στάσου σε απόσταση περίπου ενός μπράτσου από τον τοίχο.",
        "Τοποθέτησε το ένα χέρι στον τοίχο στο ύψος του ώμου· το άλλο χέρι στη μέση ή στο πλάι.",
        "Άφησε το σώμα να γείρει προς τον τοίχο σαν σφιχτή σανίδα, λυγίζοντας ελεγχόμενα τον αγκώνα.",
        "Κατέβα με αργή έκκεντρη φάση (3 δευτ.) προς τον τοίχο και σπρώξε δυνατά μακριά του."
      ],
      "tips": []
    },
    "en": {
      "name": "Wall one-arm push-up",
      "summary": "One-arm push-ups against a wall — a safe entry exercise for the one-arm progression.",
      "instructions": [
        "Stand about an arm length away from the wall.",
        "Place one hand on the wall at shoulder height; the other hand rests on the lower back or hip.",
        "Tilt the body as a solid plank toward the wall, bending the elbow under control.",
        "Lower with a slow eccentric (3 s) toward the wall, then press away powerfully."
      ],
      "tips": []
    },
    "es": {
      "name": "Flexión de un solo brazo en pared",
      "summary": "Flexiones de un solo brazo contra la pared — un ejercicio de entrada seguro para la progresión de un solo brazo.",
      "instructions": [
        "Ponte a aproximadamente la longitud de un brazo de la pared.",
        "Coloca una mano en la pared a la altura del hombro; la otra mano descansa en la zona lumbar o la cadera.",
        "Inclina el cuerpo como una plancha sólida hacia la pared, doblando el codo de forma controlada.",
        "Desciende con un excéntrico lento (3 s) hacia la pared y luego empuja con potencia."
      ],
      "tips": []
    },
    "fr": {
      "name": "Pompe à un bras contre le mur",
      "summary": "Pompes à un bras contre un mur — un exercice d'entrée sécurisé pour la progression à un bras.",
      "instructions": [
        "Tenez-vous à environ une longueur de bras du mur.",
        "Placez une main sur le mur à hauteur d'épaule ; l'autre main repose sur le bas du dos ou la hanche.",
        "Inclinez le corps comme une planche solide vers le mur, en fléchissant le coude de façon contrôlée.",
        "Descendez avec un excentrique lent (3 s) vers le mur, puis repoussez puissamment."
      ],
      "tips": []
    },
    "it": {
      "name": "Piegamento a un braccio contro il muro",
      "summary": "Piegamenti a un braccio contro una parete — un esercizio di ingresso sicuro per la progressione a un braccio.",
      "instructions": [
        "Posizionati a circa un braccio di distanza dalla parete.",
        "Appoggia una mano sulla parete all'altezza della spalla; l'altra mano poggia sulla zona lombare o sul fianco.",
        "Inclina il corpo come una plank solida verso la parete, piegando il gomito in modo controllato.",
        "Scendi con un eccentrico lento (3 s) verso la parete, poi spingi via con forza."
      ],
      "tips": []
    },
    "nl": {
      "name": "Eénarmige muropdruk",
      "summary": "Eénarmige opdrukken tegen een muur — een veilige beginoefening voor de eénarmige progressie.",
      "instructions": [
        "Sta ongeveer een armslengte van de muur af.",
        "Plaats één hand op de muur op schouderhoogte; de andere hand rust op de lage rug of heup.",
        "Kantel het lichaam als een solide plank richting de muur, buig de elleboog gecontroleerd.",
        "Zak langzaam excentrisch (3 s) naar de muur, druk dan krachtig weg."
      ],
      "tips": []
    },
    "no": {
      "name": "Enarms armhevning mot vegg",
      "summary": "Enarms armhevninger mot en vegg – en sikker inngangsøvelse for enarms-progresjon.",
      "instructions": [
        "Stå omtrent en armslengde fra veggen.",
        "Plasser én arm på veggen i skulderhøyde; den andre armen hviler på nedre del av ryggen eller hoften.",
        "Vipp kroppen som en solid planke mot veggen, og bøy albueleddet med kontroll.",
        "Senk med en langsom eksentrisk bevegelse (3 s) mot veggen, og press deretter kraftig bort."
      ],
      "tips": []
    },
    "zh": {
      "name": "墙壁单臂俯卧撑",
      "summary": "靠墙做单臂俯卧撑——单臂俯卧撑进阶中的安全入门动作。",
      "instructions": [
        "站在距离墙约一臂距离的位置。",
        "一只手放在墙面上，与肩膀同高，另一只手放在下背部或髋部。",
        "身体像平板一样倾向墙面，控制速度弯曲肘部。",
        "花3秒时间缓慢下降朝向墙面，然后有力地向外推。"
      ],
      "tips": []
    }
  },
  "wide": {
    "de": {
      "name": "Weite Liegestütze",
      "summary": "Breiter Handstand für mehr Brustaktivierung und weniger Trizeps-Belastung.",
      "instructions": [
        "Hände deutlich breiter als schulterbreit, Finger leicht nach außen.",
        "Ellenbogen zeigen seitlich, beim Absenken weiter nach außen klappen.",
        "Brust kontrolliert absenken, dabei spürbares Stretchgefühl in der Brust.",
        "Bewusst aus der Brust hochdrücken — nicht mit dem Trizeps \"schummeln\"."
      ],
      "tips": [
        "Schultergesundheit: Schulterblätter aktiv zusammenziehen, nicht in den Gelenken hängen."
      ]
    },
    "el": {
      "name": "Πιέσεις με ανοιχτή λαβή",
      "summary": "Πιο φαρδιά θέση χεριών που τονίζει το στήθος και ελαφρώνει τους τρικέφαλους.",
      "instructions": [
        "Χέρια αισθητά πιο φαρδιά από τους ώμους, δάχτυλα ελαφρώς προς τα έξω.",
        "Οι αγκώνες δείχνουν προς τα πλάγια και ανοίγουν περισσότερο κατά την κατάβαση.",
        "Κατέβασε ελεγχόμενα το στήθος με αισθητή διάταση στο στήθος.",
        "Σπρώξε προς τα πάνω συνειδητά από το στήθος — μην «κλέβεις» με τους τρικέφαλους."
      ],
      "tips": [
        "Υγεία ώμων: κράτα τις ωμοπλάτες ενεργές και μαζεμένες, μην κρέμεσαι από τις αρθρώσεις."
      ]
    },
    "en": {
      "name": "Wide push-up",
      "summary": "Wider hand placement that emphasises the chest and offloads the triceps.",
      "instructions": [
        "Hands set noticeably wider than shoulders, fingers angled slightly out.",
        "Elbows track to the sides, opening further as you descend.",
        "Lower the chest under control with a clear stretch sensation across the chest.",
        "Press up consciously from the chest — do not \"cheat\" with the triceps."
      ],
      "tips": [
        "Shoulder health: keep the shoulder blades retracted, do not hang in the joints."
      ]
    },
    "es": {
      "name": "Flexión abierta",
      "summary": "Posición de manos más abierta que enfatiza el pecho y descarga el tríceps.",
      "instructions": [
        "Manos notablemente más separadas que los hombros, dedos ligeramente hacia fuera.",
        "Los codos se abren hacia los lados, ampliándose más al descender.",
        "Baja el pecho de forma controlada con una clara sensación de estiramiento en el pecho.",
        "Empuja conscientemente desde el pecho — no \"hagas trampa\" con el tríceps."
      ],
      "tips": [
        "Salud del hombro: mantén las escápulas retraídas, no te cuelgues de las articulaciones."
      ]
    },
    "fr": {
      "name": "Pompe large",
      "summary": "Placement des mains plus large qui accentue les pectoraux et décharge les triceps.",
      "instructions": [
        "Placez les mains nettement plus larges que les épaules, doigts légèrement orientés vers l'extérieur.",
        "Les coudes s'écartent sur les côtés, s'ouvrant davantage lors de la descente.",
        "Descendez la poitrine de façon contrôlée avec une nette sensation d'étirement à travers les pectoraux.",
        "Poussez vers le haut consciemment depuis les pectoraux — ne « trichez » pas avec les triceps."
      ],
      "tips": [
        "Santé des épaules: gardez les omoplates rétractées, ne vous suspendez pas dans les articulations."
      ]
    },
    "it": {
      "name": "Piegamento largo",
      "summary": "Posizione delle mani più larga che enfatizza il petto e alleggerisce il lavoro dei tricipiti.",
      "instructions": [
        "Mani posizionate notevolmente più larghe delle spalle, dita leggermente ruotate verso l'esterno.",
        "I gomiti si aprono verso i lati, aprendosi ulteriormente durante la discesa.",
        "Abbassa il petto in modo controllato con una chiara sensazione di allungamento sul petto.",
        "Spingi su consapevolmente dal petto — senza \"barare\" con i tricipiti."
      ],
      "tips": [
        "Salute delle spalle: mantieni le scapole retratte, non cedere nelle articolazioni."
      ]
    },
    "nl": {
      "name": "Brede opdruk",
      "summary": "Bredere handplaatsing die de borst benadrukt en de triceps ontlast.",
      "instructions": [
        "Handen duidelijk breder dan schouderbreedte, vingers licht naar buiten gericht.",
        "Ellebogen bewegen naar de zijkanten, openen verder bij het zakken.",
        "Laat de borst gecontroleerd zakken met een duidelijk rek over de borst.",
        "Druk bewust vanuit de borst omhoog — niet \"vals spelen\" met de triceps."
      ],
      "tips": [
        "Schoudergezondheid: houd de schouderbladen ingetrokken, hang niet in de gewrichten."
      ]
    },
    "no": {
      "name": "Wide armhevning",
      "summary": "Bredere håndposisjon som vektlegger brystet og avlaster tricepsen.",
      "instructions": [
        "Plasser hendene merkbart bredere enn skuldrene, fingrene vinklet litt utover.",
        "Albueleddet følger til siden, åpner videre når du senker deg.",
        "Senk brystet med kontroll med en klar strekkfølelse på tvers av brystet.",
        "Press oppover bevisst fra brystet – ikke \"jukser\" med tricepsen."
      ],
      "tips": [
        "Skulderhelse: hold skulderbladene trukket sammen, ikke heng i leddene."
      ]
    },
    "zh": {
      "name": "宽距俯卧撑",
      "summary": "更宽的手部位置强调胸部，减轻三头肌的负荷。",
      "instructions": [
        "双手位置明显宽于肩膀，手指略微向外倾斜。",
        "肘部向两侧追踪，下降时进一步打开。",
        "控制速度下降胸部，整个胸部应感受到明显的拉伸。",
        "有意识地从胸部向上按压——不要\"作弊\"式使用三头肌。"
      ],
      "tips": [
        "肩关节健康：保持肩胛骨后缩，不要在关节处悬挂。"
      ]
    }
  }
};
