import nx from '@nx/eslint-plugin';

export default [
  ...nx.configs['flat/base'],
  ...nx.configs['flat/typescript'],
  ...nx.configs['flat/javascript'],
  {
    ignores: [
      '**/dist',
      '**/out-tsc',
      '**/vite.config.*.timestamp*',
      // Generated by sw-push:build — lint the TS source in libs/sw-push,
      // not the bundled artefact.
      'web/public/push/**',
    ],
  },
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    rules: {
      '@nx/enforce-module-boundaries': [
        'error',
        {
          enforceBuildableLibDependency: true,
          allow: ['^.*/eslint(\\.base)?\\.config\\.[cm]?[jt]s$'],
          depConstraints: [
            // auth must NOT depend on data-access (decoupled via ports)
            {
              sourceTag: 'scope:auth',
              onlyDependOnLibsWithTags: ['scope:models', 'scope:testing'],
            },
            // motivation must NOT depend on auth (userId passed as param)
            {
              sourceTag: 'scope:motivation',
              onlyDependOnLibsWithTags: ['scope:models'],
            },
            // data-access depends only on models
            {
              sourceTag: 'scope:data-access',
              onlyDependOnLibsWithTags: ['scope:models'],
            },
            // data-access-state owns reactive read-models (signal stores) layered
            // on top of the stateless data-access API services.
            {
              sourceTag: 'scope:data-access-state',
              onlyDependOnLibsWithTags: ['scope:models', 'scope:data-access'],
            },
            // reminders depends on data-access, data-access-state, motivation,
            // and push (NOT auth). Runtime coupling to push state is via
            // SHOULD_SKIP_IN_APP_REMINDER port, not by importing push stores.
            {
              sourceTag: 'scope:reminders',
              onlyDependOnLibsWithTags: [
                'scope:models',
                'scope:data-access',
                'scope:data-access-state',
                'scope:motivation',
                'scope:push',
                'scope:testing',
              ],
            },
            // push owns Web Push subscription state + /push/ service worker.
            // Depends on data-access for QuickLogListener (logs a pushup
            // entry from the notification action).
            {
              sourceTag: 'scope:push',
              onlyDependOnLibsWithTags: [
                'scope:models',
                'scope:data-access',
                'scope:testing',
              ],
            },
            // quick-add depends on models (+ testing for specs)
            {
              sourceTag: 'scope:quick-add',
              onlyDependOnLibsWithTags: ['scope:models', 'scope:testing'],
            },
            // auto-count depends on models only (port-only lib, no UI)
            {
              sourceTag: 'scope:auto-count',
              onlyDependOnLibsWithTags: ['scope:models'],
            },
            // ads is isolated
            {
              sourceTag: 'scope:ads',
              onlyDependOnLibsWithTags: ['scope:models'],
            },
            // sw-push is a standalone service-worker bundle — must stay isolated
            {
              sourceTag: 'scope:sw-push',
              onlyDependOnLibsWithTags: [],
            },
            // testing can depend on anything (test utilities)
            {
              sourceTag: 'scope:testing',
              onlyDependOnLibsWithTags: [
                'scope:models',
                'scope:data-access',
                'scope:auth',
              ],
            },
            // cloud-functions depends on models only
            {
              sourceTag: 'scope:cloud-functions',
              onlyDependOnLibsWithTags: ['scope:models'],
            },
            // models has no dependencies
            {
              sourceTag: 'scope:models',
              onlyDependOnLibsWithTags: [],
            },
            // app can depend on everything
            {
              sourceTag: 'scope:app',
              onlyDependOnLibsWithTags: [
                'scope:auth',
                'scope:data-access',
                'scope:data-access-state',
                'scope:models',
                'scope:reminders',
                'scope:push',
                'scope:quick-add',
                'scope:ads',
                'scope:motivation',
                'scope:auto-count',
                'scope:testing',
              ],
            },
          ],
        },
      ],
    },
  },
  {
    files: [
      '**/*.ts',
      '**/*.tsx',
      '**/*.cts',
      '**/*.mts',
      '**/*.js',
      '**/*.jsx',
      '**/*.cjs',
      '**/*.mjs',
    ],
    // Override or add rules here
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
];
