packages:
  - 'data-store/functions'

overrides:
  websocket-driver: '>=0.7.5'
  tar: '>=7.5.19'
  '@vitest/browser': '>=4.1.10'

allowBuilds:
  '@firebase/util': true
  '@nestjs/core': true
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
  re2: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@wolsok/thanos@17.0.18'

peerDependencyRules:
  allowedVersions:
    '@angular/common': '21'
    '@angular/core': '21'
    '@angular/platform-browser': '21'
    '@angular/platform-browser-dynamic': '21'
    'rxjs': '7.8'
  ignoreMissing:
    - 'zone.js'
