packages:
  - 'data-store/functions'

allowBuilds:
  '@firebase/util': true
  '@nestjs/core': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
  '@sentry/cli': true
  re2: true
  unrs-resolver: true
