packages:
  - 'data-store/functions'

allowBuilds:
  '@firebase/util': true
  '@nestjs/core': true
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
  re2: true
  unrs-resolver: true
patchedDependencies:
  '@angular/build': patches/@angular__build.patch

peerDependencyRules:
  allowedVersions:
    '@angular/common': '21'
    '@angular/core': '21'
    '@angular/platform-browser': '21'
    '@angular/platform-browser-dynamic': '21'
    'rxjs': '7.8'
  ignoreMissing:
    - 'zone.js'
